### ISSUE TITLE
NBH Digital Web Presence & Back Office

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#10]
## goal

- make sure team is up to date where all content is
- put in place the basic infrastructure
- put basic first info in place (can be very small to start with)

## Deliverables 

- [x] google
    - [x] every member of this org, on our google domain, multiple aliases
    - [x] check dir in gdrive on tf extranet (reboot), is all content there?
    - [x] create homedoc in that gdrive (link to relevant locations)
    - [x] move old info to _archive, too new to _beta
- [x] github
    - [x] create github account (access to despiegk, ...), ask Kristof to create !
    - [x] choose name usable for github,name.com  (nbhdigital?) 
- [x] private git
    - [x] create docs.grid.tf account (access to despiegk, ...)
- [ ] FFP
    - [x] check/create space(s) on freeflowpages, make sure right members are there
    - [ ] check all members are in FFP with photos
    - [ ] create roadmap on the space for the public service (see TF grid use space example)
- [ ] wiki / website
    - [ ] move/create info_ & www_ repo's in github account  (website/wiki) 
    - [ ] make sure website & wiki are on our publishing platform exposed (production,staging)
    - [x] make sure source website is there (e.g. mobirise content)
    - [ ] make sure all source for the wiki's is there
- [ ] backoffice
    - [ ] deploy production odoo & customize, requires #37
    - [ ] make sure everyone of this org exists in this odoo
    - [ ] put link in home doc on gdrive for org

## requirements

- < 5 man days work !!!
- its just a starting point so we can build team & go from there

**Comment by Sacha96** [comment]
@samtaggart @VonSub I believe this is relevant to you. Please review when free. Thanks!

**Comment by VonSub** [comment]
website has been there for a while already in the nbh-digital organisation.

https://github.com/nbh-digital/www_nbh-digital_com

**Comment by VonSub** [comment]
seems the wiki still needs to be setup.

Will fix this.

**Comment by gmachtel** [comment]
Issue blocked until we clearly know how to go forward with it (Denmark vs. Cyprus vs. combi).
