### ISSUE TITLE
ALL: Define & list owners on Home readme & individual repo readmes

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#103]
We should publicly define and state all owners across repos.

- [x] List all owners on Home readme (Foundation)

**Comment by despiegk** [comment]
put on home page of account

**Comment by samtaggart** [comment]
Home: List teams + github handles + link to kanban (single source of truth)

Individual repos: Name Team + Link back to main readme for ownership

**Comment by samtaggart** [comment]
https://github.com/threefoldfoundation/home/blob/master/README.md

@despiegk For now I only listed all of the repos we manage from publishtools. Enough or should we add more?
