### ISSUE TITLE
ALL - decide on partners which goes where 

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#109]
We have large list of partners (51) on [data_threefold](https://github.com/threefoldfoundation/data_threefold/tree/development/content/project) that needs to be featured across our websites. Please decide where which partners will go.

Specify project (website) in each partners .md file:
`tags: [ ]`

Current active projects:
twin
cloud
farming
tech
foundation
fairswap
aci
(mazraa)

**Comment by samtaggart** [comment]
Let's do this on Sunday.
