### ISSUE TITLE
ALL - site name duplicated on tab

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#110]
Is there a reason for website name to be duplicated on tab.
Can we please remove it, leaving site name being showed once?

instead of ACI - ACI, have ACI
instead of ThreeFold Farming - ThreeFold Farming, have ThreeFold Farming
etc
for all sites please.

<img width="654" alt="Screenshot 2021-02-24 at 10 27 52" src="https://user-images.githubusercontent.com/20182572/108971572-1df41800-768b-11eb-964f-2a126d26a596.png">

**Comment by ehab-hassan** [comment]
done at local
