### ISSUE TITLE
ALL: Create TF 3.0 Component and Page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#114]
We need to create a component that we can put on all pages that teases ThreeFold 3.0 launch along with a page – probably a wiki for the first version, but let's debate – that gives detailed info about what ThreeFold 3.0 is and is not.

- [ ] Component Created
- [ ] Page Created

**Comment by samtaggart** [comment]
For the component we will likely just use this (below) but change the background color to have it stand out. We don't want it to be too large or invasive and we want it to be able to fit in to all sites.

<img width="1370" alt="Screen Shot 2021-03-02 at 2 49 32 PM" src="https://user-images.githubusercontent.com/50134479/109665987-d0dadf00-7b7f-11eb-8749-895dd4e3d8a2.png">

**Comment by Sacha96** [comment]
lets work on something this week after low hanging fruits are tackled

**Comment by samtaggart** [comment]
Agreed but we need to revisit this with Kristof. When is TF 3.0, how much should we be emphasizing this, etc.

**Comment by Sacha96** [comment]
finally we are launching with 2.7 so I delete that story (outdated)
