### ISSUE TITLE
EXPERTS - Develop one-page experts website & link it to cloud / marketplace

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#117]
We have the idea for ThreeFold Experts website where people who want to use the cloud or marketplace can come in and tap into people with experience.

- [ ] Confirm with Kristof
- [ ] Create layout
- [ ] Zia create the design

Need to see if this is still relevant, with K.

**Comment by Sacha96** [comment]
didn;t come up again, and don;t think its needed after all.

**Comment by samtaggart** [comment]
Let's look into this in the future.
