### ISSUE TITLE
FORUM - lift up

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#118]
As we are inviting more and more people to join our Forum for discussions I feel we need to organise it a bit to ease navigation for people who joins for the first time.
Also add important categories such as Farming, Cloud, DigitalTwin etc.

**Comment by VonSub** [comment]
Are you on this already @Vilnite as I working on a proposal as well.

**Comment by Vilnite** [comment]
I'm done with what I wanted to improve.
Handing over to you @VonSub

**Comment by Vilnite** [comment]
Will close this issue as it's related to what I wanted to change and did change.
@VonSub please create a new issue if needed :)
