### ISSUE TITLE
CLOUD - main positioning for cloud is: the first Carbon Neutral  P2P Cloud

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#124]
# Carbon Neutral  Peer 2 Peer Cloud

- home page need to be the peer2peer message (like we used on marketplace)

**Comment by despiegk** [comment]
typo  
![image](https://user-images.githubusercontent.com/6021844/111023225-7f80ea00-83e0-11eb-96ee-c65b9227b8ab.png)

**Comment by samtaggart** [comment]
Edited language on home page and fixed the typo.
