### ISSUE TITLE
ALL - decentralization needs to become p2p

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#125]
![image](https://user-images.githubusercontent.com/6021844/111023254-a5a68a00-83e0-11eb-91b5-3f0f91872149.png)

make this picture editable and nicer
will become one of our most important slides

https://docs.google.com/presentation/d/1tRPjubgQaspXIXFV1vh8eiyBGrXAW6yuIeZbMN7a9qA/edit#slide=id.gc6f21bb149_0_106

**Comment by Sacha96** [comment]
Given all changes brought to web presence I'm pushing this to later. could be end of this week or next sprint

**Comment by Sacha96** [comment]
Didn't have time for this yet but we will try fit it in this week.
