### ISSUE TITLE
DIGITALTWIN - add WHY page

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#127]
make sure we have a P2P page (like in marketplace) for digital twin.
This is one of the most important elements.

need to explain why this is so much more efficient.

Sam: "How DT is the next evolution of privacy and freedom."

**Comment by AlexandreHannelas** [comment]
First Draft done by Zia. Need adjustment. Mock-up will be finalized early next week (web 2.7.1)

**Comment by Sacha96** [comment]
@AlexandreHannelas whats the status there?

**Comment by AlexandreHannelas** [comment]
First Mock-up: https://xd.adobe.com/view/8fdb0751-6ab9-4b72-7e92-04bf54eddc16-f9ea/?fullscreen
password: ZiaZiaZia143

Feedback Form: https://docs.google.com/spreadsheets/d/1LBa-aSOdfTvsMxPx-jPlPkAxfYJDEq8vokxvcSu3n1M/edit#gid=0

Still need adjustments. Targeting sprint 2.8 to provide final version

**Comment by Sacha96** [comment]
to me lets do minimum edits and push it live at end of sprint

**Comment by AlexandreHannelas** [comment]
Talk to Zia, will be finalized on Monday

**Comment by Vilnite** [comment]
@ehab-hassan @samaradel  please navigate this work between you two.

**Mockup:**
https://xd.adobe.com/view/8fdb0751-6ab9-4b72-7e92-04bf54eddc16-f9ea/?fullscreen
password: ZiaZiaZia143

AI file sent on telegram.
