### ISSUE TITLE
link website dbank, private to tftech

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#13]
- [ ] make sure link documented in
    - https://github.com/threefoldfoundation/home/edit/master/README.md
    - link to source repo which needs to be in https://docs.grid.tf/org/ThreeFold.Tech/dashboard
- [ ] make sure gitea repo exists for the website 
- [ ] make sure is automatically published on our web infrastructure (zos based)
- [ ] make sure source of mobirise is there
- [ ] document passwd on the gitea repo

**Comment by nbabenko** [comment]
Task moved into trello https://trello.com/c/gFgnqy6Q/96-link-website-dbank-private-to-tftech
