### ISSUE TITLE
ALL: Impressums are needed

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#132]
- [ ] threefold.io
- [ ] farming
- [ ] cloud
- [ ] marketplace
- [ ] twin
- [ ] aci
- [ ] tech (different than foundation)

**Comment by samtaggart** [comment]
@VonSub I think this is important to be done this week BEFORE Thursday. Please update.

**Comment by VonSub** [comment]
Agreed, I pinged @down2basics to see if we have all we need to do so and who owns the websites TF LAbs or TF Swiss...
