### ISSUE TITLE
ALL - specify tags and categories - what projects/people/content will go to which website and how are they ranked

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#133]
Need to make sure we are consistent in tagging our partners, people and content.
Which content goes to which website, and how do we filter it, by what tags?
And how are we ranking?

- [x] decide on variables used for people/projects/blog/news
- [x] update data_threefold readme
- [x] update projects
- [x] update people
- [x] create an issue for devs to update on backend

**Comment by Vilnite** [comment]
Related issues on development side
- update categories and tags that will pull content in each website:  https://github.com/threefoldfoundation/data_threefold/issues/29
- make sure ranking works: https://github.com/threefoldfoundation/data_threefold/issues/30
- add tags to each person and project overview and detail page:  https://github.com/threefoldfoundation/home/issues/152

**Comment by samtaggart** [comment]
Updated all people – tags, categories, and ranking – to the best of my knowledge.
