### ISSUE TITLE
ALL WIKI'S - redirect all old wiki domains to new ones

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#134]
Please make sure all old wiki domains are redirected to `new.threefold.io/info/<name>`:
- [x] wiki.threefold.io = new.threefold.io/info/threefold
- [x] wiki.twin.threefold.io = new.threefold.io/info/twin
- [x] wiki.cloud.threefold.io = new.threefold.io/info/cloud
- [x] wiki.sdk.threefold.io = new.threefold.io/info/sdk
- [x] wiki.legal.threefold.io  = new.threefold.io/info/legal
- [x] info.threefol.io (info.tftech) = ?? Do we have it under `new.threefold.io`? need to link as well

Please do it for websites as well:
- [x] threefold.io = new.threefold.io
- [x] twin.threefold.io = new.threefold.io/twin
- [x] cloud.threefold.io = new.threefold.io/cloud
- [x] farming.threefold.io = new.threefold.io/farming
- [x] marketplace.threefold.io = new.threefold.io/marketplace
- [x] consciousinternet.org = new.threefold.io/aci
- [x] threefold.tech = ?? Do we have it under `new.threefold.io` ? need to link as well

**Comment by Pishoy** [comment]
all fixed excpet the aksing ones

**Comment by Pishoy** [comment]
all done

**Comment by sasha-astiadi** [comment]
hi kristine i hope its gonna be put as top priority because we despretaly need it for tf connect app @Vilnite

**Comment by sasha-astiadi** [comment]
- [ ]  wiki.threefold.io/#/legal = new.threefold.io/info/legal

- [ ] legal.threefold.io = new.threefold.io/info/legal

correction and addition of legal redirects @Hamdy @Pishoy

**Comment by sasha-astiadi** [comment]
@Vilnite still no redirect from these
 wiki.threefold.io/#/legal = new.threefold.io/info/legal

 legal.threefold.io = new.threefold.io/info/legal

**Comment by Vilnite** [comment]
Ok, so wo need tp redirect https://wiki.threefold.io/#/legal (currently broken link on TF Connect) to https://threefold.io/info/threefold#/legal__legal

**Comment by Vilnite** [comment]
Ok, so wo need tp redirect https://wiki.threefold.io/#/legal (currently broken link on TF Connect) to https://threefold.io/info/threefold#/legal__legal

**Comment by Hamdy** [comment]
This redirect Can not happen.
# in domain name means it's client side url not recognized by server 
so https://wiki.threefold.io/#/legal   means basically you want  basically to redirect https://wiki.threefold.io to another link
in this case we loose https://wiki.threefold.io
It has to be done on mob app level

**Comment by Vilnite** [comment]
@sasha-astiadi looks like we need to update app after all 🤷
