### ISSUE TITLE
ALL: Mailing List Signup Popup

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#137]
- [x] Change "Signup for the ThreeFold newsletter" to "Sign up for the ThreeFold mailing list to receive general project updates!"
- [x] Make sure group on Mailerlite is ThreeFold Foundation Main Group (all websites which have a mailing list popup should add signups to this group)

**Comment by ehab-hassan** [comment]
@VonSub can u give me access at MailerLite account so I can change the text here

**Comment by samtaggart** [comment]
info@threefold.io
7Z*CUkJr.n3YFTU

**Comment by ehab-hassan** [comment]
![ThreeFold-MailerLite](https://user-images.githubusercontent.com/10484295/112751472-83129480-8fce-11eb-80af-ba6ae4505f06.png)
I checked that all mails at signup Subscriber here ThreeFold Foundation main group

@VonSub please confirm tomorrow from your side that all working good

**Comment by VonSub** [comment]
verified; works.
