### ISSUE TITLE
DIGITALTWIN - have a separate top level domain address for the website in order to comply with paypment processor requirements

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/home#139]
If we apply for the payment provider with twin.threefold.io, they will have to asses threefold.io business before approving our application. Much better will be to choose top level domain, something like digitaltwin.io and assign it as an alternative address to our Digital Twin website. 
[ ] Choose and buy top domain address
[ ] Update DNS

**Comment by AlexandreHannelas** [comment]
Bought the domain - mydigitaltwin.io

**Comment by AlexandreHannelas** [comment]
New DT website and Wiki URL:
Website url: mydigitaltwin.io
Wiki url: info.mydigitaltwin.io

**Comment by AlexandreHannelas** [comment]
New DT website and Wiki URL:
Website url: mydigitaltwin.io
Wiki url: info.mydigitaltwin.io
