### ISSUE TITLE
link token promotion website to repo

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#14]
- [ ] make sure link documented in
    - https://github.com/threefoldfoundation/home/edit/master/README.md
    - link to source repo which needs to be in https://docs.grid.tf/org/threefold/dashboard (is right now in github despiegk, move it from there)
- [ ] make sure gitea repo exists for the website 
- [ ] make sure is automatically published on our web infrastructure (zos based)
- [ ] make sure source of mobirise is there
- [ ] document passwd on the gitea repo

**Comment by Sacha96** [comment]
@despiegk is this still relevant? If yes please assign someone. If no please close the issue. Regards.
