### ISSUE TITLE
ALL: Go through metadata of every page on every site

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#140]
I see a lot of pages across websites with bad metadata.

Each page of each site needs:

- Title
- Description
- Image

Check for:

- [ ] threefold.io
- [ ] farming
- [ ] aci
- [ ] marketplace
- [ ] cloud
- [ ] twin
- [ ] tech

**Comment by Vilnite** [comment]
@samtaggart I don't think we need to do this together.
We already updated successfully all home pages for each website, I think it's just a matter of listing all other pages and providing metadata that we wanna apply there and assigning it to Samar for execution.

**Comment by samtaggart** [comment]
@Vilnite Well anyone can do it but indeed I will handle. Will try to get to it this weekend & will assign @samaradel.

**Comment by samtaggart** [comment]
Done here: https://secure.threefold.me/pad/#/2/pad/edit/9Qx-+GVbLeS812ZjtQ3WaI1A/

Will create a new issue for this to be implemented by Samar.
