### ISSUE TITLE
Please update wiki list view on new.threefold.io/info

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#144]
We need to update css of current list:
- [x] remove errors
- [x] use font from threefold_io website
- [ ] separate Related Project wikis from ThreeFold wikis (if not possible please remove those 3 - tag, uhuru, mitaa)

![wiki_list_page](https://user-images.githubusercontent.com/20182572/112446540-ff03a700-8d58-11eb-939d-3cfd3535eeac.png)

**Comment by samaradel** [comment]
Done @Hamdy please check 3rd point and waiting for node update

**Comment by Vilnite** [comment]
remove tech from there

**Comment by Vilnite** [comment]
add legal
