### ISSUE TITLE
DNS - tech website/wiki can't link to new.threefold.io

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#145]
http://info.threefold.io points to https://new.threefold.io/info/tftech which is wrong location

- [ ] http://info.threefold.io needs to point to https://new.threefold.io/info/threefold, not tftech wiki
- [ ] tftech wiki http://info.threefold.tech remains where is and needs to be behind username/passwd (ask @Vilnite ) >> THIS INFO IS NOT PUBLIC !!!

**Comment by Hamdy** [comment]
Can't be done, due to the fact that ssl.is working on publisher server side , domain support need to.be added there

**Comment by Vilnite** [comment]
@AlexandreHannelas please note that same issue then goes for separating twin website from new.threefold.io/..
