### ISSUE TITLE
ALL  - please go through all websites and check/fix mobile responsiveness

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#146]
Please make sure all our websites are mobile friendly and that there are no glaring errors:
- [x] threefold_io
- [x] cloud
- [x] twin
- [x] farming
- [x] marketplace
- [x] aci
- [x] threefold.tech

**Comment by Vilnite** [comment]
In the News section both on threefold_io and farming stretches logos on mobile view:
please ping me when on it I have logos for mobile resolution.

- [ ] news logos for mobile fixed on tf_io
- [ ] news logos for mobile fixed on farming

**Comment by ehab-hassan** [comment]
I think all glaring errors fixed 
feel free to add issue if u find something

**Comment by Vilnite** [comment]
In The News on threefold.io and farming still have issues with responsiveness.
Please fix. 

- [ ] mobile
![2021-04-15 10 23 35](https://user-images.githubusercontent.com/20182572/114830255-b7f75780-9dd4-11eb-830a-980371e66135.jpg)

- [ ] latest Safari on Mac (Big Sur) same for latest Safari iOS

![2021-04-15 10 23 47](https://user-images.githubusercontent.com/20182572/114830373-cc3b5480-9dd4-11eb-9ac5-9a932f5f03f5.jpg)

**Comment by ehab-hassan** [comment]
it seem fixed but lets keep issue open until we check at production

**Comment by Vilnite** [comment]
We also need to double check digital twin website, @AlexandreHannelas pointed out several issues on mobile there.

**Comment by AlexandreHannelas** [comment]
To be checked/fixed: 

Overall website (Both landscape and Portrait)
- [ ] Load time for the website (high for the moment) 
- [ ] Home: Digital Twin Applications logo is pixelated 
- [ ] Experience pages: When clicking on each experience page, top page needs to be Digital Twin [Experience name] logo. Bring telegram channel block between CTA and Footer. 
- [ ] All experience logos are pixelated on the features page
- [ ] In each experience feature page, make each text consistent with other features block text (some texts are too small to read properly)
- [ ] Pay Once Benefit Forever CTA image pixelated everywhere on website
- [ ] Home: Make sure that the arrow for each element in header back gets back to default when closing the drop-down menu
- [ ] Home: "A World Without the Digital Twin" blocks are pixelated 
- [ ] Home: "Set Yourself Free with the Digital Twin" blocks are too small to reach text - Increase size (without pixelating it)

On portrait: 
- [ ] Put burger menu top right and aligned with Digital Twin logo 
- [ ] Everywhere: When you click anywhere on the page, it opens the burger menu 
- [ ] Why: reduce page between "The current internet structure simply cannot provide this level of security" logo and next block 
- [ ] Why: "Companies have full access to everything you do" title - need to be centered 

On landspace: 
- [ ] menu icon not centered and aligned properly 
- [ ] Home: center "A World Without the Digital Twin" blocks
- [ ] Not possible to see all elements in Universe, Experiences, Learn, About us drop-down menu in header - Make possible to slide through all elements 
- [ ] In About us drop-down menu, text gets cut 
- [ ]  Home: "Set Yourself Free with Digital Twin" blocks are pixelated 
- [ ]  Aligned DT logo with label in footer (See photo) 
![IMG_7359](https://user-images.githubusercontent.com/78421574/115141309-cc895900-a03b-11eb-8436-3cd8972ea2a4.PNG)
- [ ] Why: CTA "Get Your DigItal Twin for Life Now" - text too close to the borders 
- [ ] Home: Partners logo pixelated

**Comment by Vilnite** [comment]
- [ ] On threefold_io navbar doesn't collapse when selecting pages:

![IMG_9114](https://user-images.githubusercontent.com/20182572/115278185-d7cca980-a14d-11eb-8e48-b97a1132c126.PNG)

**Comment by AlexandreHannelas** [comment]
Tested on mac and iphone

**Comment by ehab-hassan** [comment]
what is size of make resolution?

**Comment by ehab-hassan** [comment]
![image](https://user-images.githubusercontent.com/10484295/115387454-fd53c480-a1da-11eb-8131-7e159654c15b.png)
this image working fine at mobile and desktop not pixelated acually will go throw all website and resize and optmtmiz images to reduce load time (not all image can be svg)

**Comment by AlexandreHannelas** [comment]
my mac resolution: 1440 x 900 

On my Iphone 8, it is pixelated 
![IMG_7371](https://user-images.githubusercontent.com/78421574/115388497-3e000d80-a1dc-11eb-951d-f5c25d08fac5.PNG)


![IMG_7372](https://user-images.githubusercontent.com/78421574/115388482-380a2c80-a1dc-11eb-8359-da38094759b1.PNG)

**Comment by ehab-hassan** [comment]
@AlexandreHannelas according to our talk at telegram that is cache issue at your browser .So can u please update issue with the point need to be fixed and delete the other(fixed with hard refresh)

**Comment by ehab-hassan** [comment]
@AlexandreHannelas send me screen shot of home page to see what fixed after hard refresh

**Comment by AlexandreHannelas** [comment]
After hard refresh: 
- [ ] missing the title and text for the block: "The hidden cost of data manipulation"

![IMG_7374](https://user-images.githubusercontent.com/78421574/115715760-c4515680-a378-11eb-9f79-9b8ebd1ed156.PNG)

Still pixelated for the following: 

- [ ] Partners logo pixelated - mobile landscape 

![IMG_7380](https://user-images.githubusercontent.com/78421574/115716189-375acd00-a379-11eb-9e97-0bcbcd10d4a8.PNG)

- [ ] Pay Once benefit forever CTA pixelated on both mobile landscape and portrait 

![IMG_7378](https://user-images.githubusercontent.com/78421574/115716161-3033bf00-a379-11eb-981b-35491f4e7178.PNG)

![IMG_7377](https://user-images.githubusercontent.com/78421574/115716146-2b6f0b00-a379-11eb-9ee1-e82c94cc2dc1.PNG)

- [ ] A world without Digital Twin blocks pixelated on both mobile landscape and portrait 

![IMG_7376](https://user-images.githubusercontent.com/78421574/115716121-2447fd00-a379-11eb-9f61-648c203ee041.PNG)

![IMG_7375](https://user-images.githubusercontent.com/78421574/115716091-1befc200-a379-11eb-8aba-72c4c68a709c.PNG)

**Comment by ehab-hassan** [comment]
for pixilation issue I tested it many iPhone and mac and working fine no idea is that is related to just Iphone old version or what!!
[4D4FA314-C717-4893-9447-1B6BF036134A.pdf](https://github.com/threefoldfoundation/home/files/6419552/4D4FA314-C717-4893-9447-1B6BF036134A.pdf)
![photo_2021-05-04_09-28-31](https://user-images.githubusercontent.com/10484295/116972343-27b57f80-acbb-11eb-872f-7975dd2faf33.jpg)
![photo_2021-05-04_09-28-41](https://user-images.githubusercontent.com/10484295/116972351-2a17d980-acbb-11eb-8395-f5da19af5877.jpg)

**Comment by Vilnite** [comment]
I'm closing this issue, as it has become unreadable.
Please make sure mobile responsiveness and images are checked after production update today, and if still issues found address them in short and concise new issues.

Thank you.
