### ISSUE TITLE
ALL - fix broken links

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#149]
**THREEFOLD_IO**
- [x] **ALL** links that goes outside current website (wiki’s, other websites) needs to be external aka open in new tab _(Navbar, Footer, Buttons)_

**FARMING**
**Why** page
- [x] Meet the New Internet (broken)

**Tech** page
- [x] Dive into the Tech (broken)
- [x] ZeroOS, Learn More (broken)
- [x] Zero People. Learn More (broken)

**3Node** page
- [x] Pre-Register Today (broken)

**Token** page
- [x] Check out the Token Wiki (broken)
- [x] Get TFT (broken)

- [x] **ALL** links that goes outside current website (wiki’s, other websites) needs to be external aka open in new tab _(Navbar, Footer, Buttons)_

**CLOUD**
- [x] **ALL** links that goes outside current website (wiki’s, other websites) needs to be external aka open in new tab 

**MARKETPLACE**
**Navbar **
- [x] Learn (broken) 

**Home** page
- [x] Know More (broken) - should link to: https://new.threefold.io/info/cloud#/cloud__evdc_marketplace
- [x] Learn More (broken)

**Footer**
- [x] Participate/Applications (broken)

- [x] **ALL** links that goes outside current website (wiki’s, other websites) needs to be external aka open in new tab _(Navbar, Footer, Buttons)_

**Comment by samtaggart** [comment]
SOME ADDITIONS:

FARMING
- [ ] 3NODE: TF Grid Explorer should go to https://explorer.threefold.io
- [ ] FOOTER: Join Farmer Chat needs to go to https://t.me/joinchat/B2ISCkNpZjNv7WJ2eiNJJw

CLOUD
- [ ] FOOTER: Knowledge Base should go to cloud wiki

TECH
- [ ] "Visit threefold.io" doesn't work – should link to https://new.threefold.io
