### ISSUE TITLE
link mazraa website

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#15]
- [ ] make sure link documented in
    - https://github.com/threefoldfoundation/home/edit/master/README.md
    - link to source repo which needs to be in https://docs.grid.tf/org/...mazraa account
- [ ] make sure gitea repo exists for the website 
- [ ] make sure is automatically published on our web infrastructure (zos based)
- [ ] make sure source of mobirise is there
- [ ] document passwd on the gitea repo 
- [ ] make sure its in mobirise (if not let someone convert it quickly)

**Comment by Sacha96** [comment]
@despiegk could you please assign this to somebody. I moved it to next week's sprint.

**Comment by AdnanFatayerji** [comment]
convert Mazraa.io website to a mobirise/pendengo, @VonSub can you work your magic on this one? I'm available to support with content/images when ready.
