### ISSUE TITLE
ALL - add tags to people and projects

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#152]
This has been quite messy before but we have updated tags for all people and projects on data_threefold, and we need to 

- [x] bring tags back for people and projects overview on ALL websites,
- [x] make sure they ALL are showing for each person and project in all filter views
- [x] make sure when clicking on tags it filters out all people / projects with respective tag

Projects example:
![partners](https://user-images.githubusercontent.com/20182572/113005755-68325280-917d-11eb-9c5a-1ef8b4434cc2.png)

People example:
![people](https://user-images.githubusercontent.com/20182572/113005784-6c5e7000-917d-11eb-99d2-9bc74e37e383.png)

**Comment by samaradel** [comment]
- [ ]  threefold_io
- [ ]  farming
- [ ]  cloud
- [ ]  twin
- [ ]  marketplace
- [ ]  tech
- [ ]  aci
