### ISSUE TITLE
DIGITALTWIN - Remove Threefold Logo on DT experience portal add DT icon in Favicon

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/home#153]
We need favicon for the digitaltwin app itself (https://digitaltwin.jimbertesting.be/). Right now it is using ThreeFold logo.

**Comment by nbabenko** [comment]
![photo_2021-04-01_16-31-48](https://user-images.githubusercontent.com/4426772/113302098-65b03400-9308-11eb-8c4d-f40ea533669b.jpg)
![photo_2021-04-01_16-35-25](https://user-images.githubusercontent.com/4426772/113302104-6648ca80-9308-11eb-92b7-d2858a10789d.jpg)

**Comment by AlexandreHannelas** [comment]
Favicon sent to @sasha-astiadi 
Remove Threefold Logo and Keep "digitaltwin" label

**Comment by AlexandreHannelas** [comment]
Any update regarding this issue? @sasha-astiadi @ken-de-moor
