### ISSUE TITLE
TFT does not show up in interstellar

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#157]
![image](https://user-images.githubusercontent.com/6021844/113501266-0f1f4180-9524-11eb-9b6f-c6f27b15e36e.png)
lets get in contact with them

**Comment by nbabenko** [comment]
Currently our token is not verified on interstellar. It is possible to trade it using unverified section tab:
<img width="1423" alt="Screenshot 2021-04-04 at 10 10 55" src="https://user-images.githubusercontent.com/4426772/113501548-a5586500-952e-11eb-8119-c590b666a20d.png">
<img width="780" alt="Screenshot 2021-04-04 at 10 13 09" src="https://user-images.githubusercontent.com/4426772/113501550-a8535580-952e-11eb-9d33-6bc508b4ce73.png">
<img width="1432" alt="Screenshot 2021-04-04 at 10 13 19" src="https://user-images.githubusercontent.com/4426772/113501552-a8535580-952e-11eb-860b-804bad673387.png">

We will try to contact them to get our token to the verified tab.

**Comment by samtaggart** [comment]
I see TFT listed when I type TFT ... @nbabenko @despiegk I guess this is resolved? Or am I missing something?

<img width="1216" alt="Screen Shot 2021-04-06 at 11 49 51 PM" src="https://user-images.githubusercontent.com/50134479/113776696-d99c7300-9732-11eb-8b31-38153a7297b8.png">

**Comment by nbabenko** [comment]
yes, tested on a completely new wallet, fixed now.
