### ISSUE TITLE
TF_IO: Improve Token Buyer Journey

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#158]
WE WANT THE TOKENS TO GO UP IN VALUE, WHY IS THE WEBSITE NOT REFLECTING THIS

PLEASE, check our presence and make sure our target audience will find what they need

- people need to get to tokens news/info from first page
- explorer with capacity is crucial need to be found from first page
- ...

**Comment by Sacha96** [comment]
token is on main page on local, tomorrow token page will be brought to the website and that will give all info about token. Explorer is already on main page on local.

**Comment by Vilnite** [comment]
Addressed with issue: https://github.com/threefoldfoundation/www_threefold_io/issues/54

**Comment by Sacha96** [comment]
according to conversations with token guys (@maximilianrang @BenjellounO @nbabenko) key project information that is important to token buyer :

- roadmap needs to be created
- network stats (grid stats and token stats)
- token distribution (was edited and reviewed on wiki @ token_overview)
- partners (with edits to data_threefold all partner details are as up to date as we could make it)
- important news/ coverage (this is already there)
- why threefold token (with its utility well explained everywhere this is good)

So I will make:
- [ ] network stats (explorer) more prominent in wiki
- [ ] network stats (explorer) more prominent on threefold.io
- [ ] network stats (explorer) more prominent on threefold.io/farming
- [ ] network stats (explorer) more prominent on threefold.io/cloud
- [ ] add link to stellar expert for token stats in wiki 
- [ ] add link to stellar expert for token stats on  threefold.io
- [ ] add link to stellar expert for token stats on  threefold.io/farming

Other thing we can do is the roadmap maybe @despiegk we can align whenever you can to do this and bring it up together

**Comment by Sacha96** [comment]
Also @weynandkuijpers shared the following:

Also - having had some interaction with the new people on the "testes" telegram group (which seems to be the landing place for everyone these days). The request was to have a "simple" how to get started. Token purchase, token farming and token staking (not with us -> partners (future))
