### ISSUE TITLE
TFTA wrongly defined

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#159]
```

## TFTA

TFTA is a proxy token, migrated from the previous version of ThreeFold Grid blockchain, called Rivine. 
```

comes from stellar_blockchain

this is not the positioning we want

TFTA is a volutary staking token

**Comment by despiegk** [comment]
se should not overload concepts/defs with info

this needs to go to the right subsections

also it needs to be more modular, now we go from TFTA to Stellar to ...

way too much in 1 page

![Uploading image.png…]()

**Comment by Sacha96** [comment]
@despiegk would removing TFTA from stellar_blockchain work? Not very clear, please elaborate..

**Comment by Sacha96** [comment]
Went through wiki and couldn't find the information so I'm closing this issue
