### ISSUE TITLE
enable enertia

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#16]
- [x] enable wiki & website on github: https://github.com/enertia-io 
- [x] make wiki & website are automatically published on our web infrastructure (zos based)
- [x] for website make sure source of mobirise is there
- [x] for website document passwd on the gitea repo 
- [x] for website make sure its in mobirise (if not let someone convert it quickly)
- [x] make sure gitea account in docs.grid.tf exists & give despiegk, nickolay, ... access
- [x] define milestones 1.0.0 & 1.0.1 and 1.1.0 on all repo's
- [x] apply labels like in threefold (ask reem to help)
- [x] make sure link documented in https://github.com/threefoldfoundation/home/edit/master/README.md

**Comment by nbabenko** [comment]
http://enertia.io
https://github.com/enertia-io

Everything is done, except:
- Wiki is about to be deployed
- Autodeployment is about to be set up
- Milestones preparation is in progress

**Comment by nbabenko** [comment]
- https://github.com/enertia-io/info/issues/1 task for wiki deployment.
- Autodeployment is done
- First milestone defined
- Task to define second milestone: https://github.com/enertia-io/www_enertia_tech/issues/8
