### ISSUE TITLE
Update Coingecko, CoinMarketCap, Others

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#160]
- [x] Identify all locations where TFT is listed
- [x] List locations, assign owners
- [x] Create new content (@samtaggart)
- [x] Reach out to CoinMarketCap with new info, ask them to update Grid Explorer to https://explorer.threefold.io, about tags (what are other possible tags we can have?) (@samtaggart)
- [x] Reach out to Coingecko with new info, ask them to update Grid Explorer to https://explorer.threefold.io, ask them to check the all-time-high price, ask about tags (what are other possible tags we can have?) (@samtaggart)
- [x] Coingecko info updated
- [x] CoinMarketCap info updated

TFT is listed on CoinMarketCap & GoinGecko alongside a number of medium and small tier locations which typically take their info from one of these big two.

**Comment by Sacha96** [comment]
Update please???

**Comment by samtaggart** [comment]
We need to finalize the text ASAP and send to CoinGecko and CoinMarketCap this evening.

**Comment by samtaggart** [comment]
Information sent to CoinMarketCap via form and CoinGecko via Telegram message. @BenjellounO will hound his contacts to get these updated by tomorrow.

**Comment by samtaggart** [comment]
Updated on both CMC and CoinGecko!
