### ISSUE TITLE
2.X? MAINNET launch annoucement, TBD

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#169]
**DESCRIPTION:**
"If we wait for 3.0 we may loose that momentum. Need to organise websites and wiki updates around 2.7 launch announcement. Prep weekly partner updates, blog posts and news."

Ideally we should have the following
- [ ] Get partner Quotes (@samtaggart)
- [ ] Organize Community Call with partners and actors (Ex: Casper, Digibyte, Winston Ma and Andrea)
- [ ] Pr X Amazix
- [ ] Blog around CyberPandemic
- [ ] Blog no bandaid approach
- [ ] Blog Partners Interlinking for sustainable ecosystem
- [ ] News around 2.7 Launch
- [ ] News around carbon neutral Grid and Cloud

**Comment by Sacha96** [comment]
the announcement for mainnet is next week so remove from 2.8.1.

**Comment by Sacha96** [comment]
Finally we won't launch with 2.7 let's rediscuss before closing issue.
