### ISSUE TITLE
ALL: Add Updated Open Graph Metadata to every page across websites

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#170]
https://secure.threefold.me/pad/#/2/pad/edit/9Qx-+GVbLeS812ZjtQ3WaI1A/

- [x] threefold.io
- [x] farming
- [x] cloud
- [x] marketplace
- [x] digital twin
- [x] aci
- [x] threefold tech

Please let me know if any page is missing or if you have any questions.

*Note: We will create another issue for all the apps on Marketplace plus the main wikis.*

**Comment by ehab-hassan** [comment]
we can't have Open Graph Metadata to every page we have one header for all pages even if we do that for home we have one single page (MarkdownPage.vue) for other pages
so should we go with home Open Graph ?

**Comment by samtaggart** [comment]
What do you mean? Individual pages cannot have unique open graph data?

Maybe I'm using the wrong terminology but I'm sure that each page can have different data so that when it's shared on social media, it comes up as specifically to that page.

**Comment by ehab-hassan** [comment]
according to our conversation with @samtaggart at telegram  
we agree that each website ll have one open graph data (we ll use the home)
