### ISSUE TITLE
WIKIS + Explorer + Token Stats: Open Graph Tags

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#172]
Add open graph tags to wikis:

**MAIN WIKI**

Title
ThreeFold | Knowledge

Description
All you need to know about ThreeFold.

Image
First image being used here: https://wiki.threefold.io/#/

**CLOUD WIKI**

Title
ThreeFold P2P Cloud | Knowledge

Description
All you need to know about the ThreeFold P2P Cloud and its offerings.

Image
First image being used here: https://threefold.io/info/cloud#/

**SDK**

Title
ThreeFold | Grid Manual (SDK)

Description
All you need to know about how to create and deploy IT Solutions on top of the ThreeFold P2P Cloud.

Image
First image being used here: https://threefold.io/info/sdk#/

**GRID EXPLORER**

Title
ThreeFold | Grid Capacity Explorer

Description
Dive into live statistics around the ThreeFold Grid.

Image
Grid map from: https://threefold.io/farming

**TOKEN STATS**

Title
ThreeFold | Token Statistics (TFT)

Description
Dive into live statistics around the ThreeFold Token (TFT).

Image
Top image from: https://threefold.io/token

**Comment by samtaggart** [comment]
@Hamdy @Vilnite Feel free to move this to 'next' if it can't be done on Sunday. I just needed to assign something and will always choose 'now' instead of 'next.' :)

**Comment by Vilnite** [comment]
This issue apparently only Hamdy can handle atm and he's on a vacation.
@Hamdy please take care of it when you're back.

**Comment by Hamdy** [comment]
support for opengraphs for wikis added to latest publish tools
@Vilnite what is GRID EXPLORER & TOKEN STATS ? do we have wikis with that ?

**Comment by Hamdy** [comment]
please follow up with @hossnys for any further opengraphs that needs to be added or updated

**Comment by Vilnite** [comment]
@hossnys can you please update open graph tags for Grid Explorer : https://explorer.threefold.io, as asked in description of this issue.
Repo: https://github.com/threefoldtech/tfexplorer/issues/303 
 
FYI, Token Stats page is down and all info now is in threefold.io/info/threefold so ignore that part.

**Comment by Vilnite** [comment]
After a little bit of an investigation conclusion: it's too much of a hustle to update explorer. It's not a broadly used site and open graph tags are not critical element. Closing the issue.
