### ISSUE TITLE
Fix TF Tech legal documents.

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/home#177]
See These issues:

- https://github.com/threefoldtech/www_threefold_tech/issues/57
- https://github.com/threefoldtech/www_threefold_tech/issues/59
- https://github.com/threefoldtech/www_threefold_tech/issues/62

**Comment by Vilnite** [comment]
Please make sure all these are implemented properly - not referring to threefold.io

**Comment by ehab-hassan** [comment]
done at development
