### ISSUE TITLE
forum has wrong language, 3bot no longer used

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#179]
![image](https://user-images.githubusercontent.com/6021844/118440541-1ec7a380-b6e8-11eb-87dd-b2956f5664e2.png)

**Comment by Vilnite** [comment]
Updated category, description and language where 3Bot connect was still used.

**Comment by hossnys** [comment]
fix done on [staging](https://staging.forum.threefold.io/) now , will apply on production on Sunday to avoid annoying forum users.

![Screenshot from 2021-06-02 16-50-06](https://user-images.githubusercontent.com/26298009/120502602-db955200-c3c2-11eb-8b5f-db80b52298d0.png)
