### ISSUE TITLE
Fix public chat

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#181]
**Description:**
We get a lot of low vibrations coming in on our public chat. We want to shift to positive vibes and support mode around our project.

See: https://github.com/threefoldfoundation/info_threefold/issues/28
Development Branch: development_plan

**To Do:**
- [x] needs story about having chat rules done
    - on wiki (see https://github.com/threefoldfoundation/info_threefold/issues/28)
- [x] make sure amazix will use our guidelines
- [x] Kristof approval
- [x] make sure community understands (post on chat)
- [x] reach out to vocal guys where we don't know if they mean well, if they don't wanna expose their identity, block
- [x] make sure our own team knows how to deal with this, and we don't have to be checking the chat all the time

**Deliverable:**
- Our team understands how to keep the vibration high after the To-Dos are fulfilled

**Deadline:**

**Comment by samtaggart** [comment]
Sacha put the note through Grammarly and I did some additional editing / shot to AmaZix for feedback. Next step is we will put it on our wiki and shoot it out to the community.

**Comment by samtaggart** [comment]
Consider this issue done. We didn't reach out to anyone yet because the chat has quieted down but AmaZix and the stakeholders all know what to do.
