### ISSUE TITLE
AIBC Summit, Dubai

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#184]
**Description:**
AIBC Summit gathers many blockchain players and investors in the scene. We want to get more visibility and connections via this event.

**To Do:**
- [x] Secure spot / position in AIBC conference : https://github.com/threefoldfoundation/home_private/issues/149
- [ ] Design booth for AIBC : https://github.com/threefoldfoundation/home_private/issues/151

**Deliverable:**

**Deadline:**
24th May

**Comment by Vilnite** [comment]
created a separate project for this

**Comment by maximilianrang** [comment]
[THREEFOLD @ AIBC 2021 Stand Design Version-1 (2).pdf](https://github.com/threefoldfoundation/home/files/6521209/THREEFOLD.%40.AIBC.2021.Stand.Design.Version-1.2.pdf)
final booth design done
