### ISSUE TITLE
Add missing announcements to Newsroom, ThreeFold Connect, and Wiki

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#186]
- [x] Add missing announcements to Wiki
Wiki Markdown: https://secure.threefold.me/code/#/2/code/edit/G6OERRub+SZnTs4etu9XpJEX/
- [x] Add missing announcements to NewsRoom
- [x] Add missing announcements to ThreeFold Connect
- [x] Verify all three

**Comment by samtaggart** [comment]
@VonSub Can you help me with this tomorrow?

I did all the markdown for the wiki for the announcements section. But I can't get into my publish tools so I can't upload the files.

We then need to add missing announcements to TF Connect and to the Newsroom.

If we do a 10 minute call tomorrow I can explain.

**Comment by samtaggart** [comment]
Also I have all of the images sized correctly, I can send them to you via Telegram.

**Comment by VonSub** [comment]
All we need to do is add categories to the news, I've added the tags... unsure which is which rn.
