### ISSUE TITLE
Production update ability

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#193]
It's 2nd time in past weeks we ran into urgent need of an update of our web presence during 'off hours'.
This is gonna get more and more a necessity as we keep raising traction and eyes on ourselves.

There need to be more people able to push updates. Especially people who can step in at 'off hours'- myself, for example. 

Please come up with a solution and provide next steps in comments.

**Comment by Hamdy** [comment]
Sounds like a communication issue and has either one of 2 reasons
- Responsible team didn't commuicate that they are about to do something/sell something a head of time (before weekend)
- There was missing/undervalued priority of doing something that suddenly became important on a week end

On both cases, this is not a mistake ffrom our side at all! and we are not supposed to be blamed on this.
Please find where is correct issue and start fixing please!

On the other side, we have operation team (@hossnys ) & (@PeterNashaat ) are on call for such emergencies
so please if there's an emergency you can contact one of them or (@ramezsaeed) operations team lead
note also on the worst case scenario  that kds has access to building websites, he can build a website locally and push that particular website to production as well

**Comment by ramezsaeed** [comment]
We should avoid pushing something to production during the weekend, actually this can solve the problem.

everything should be planned and pushed before weekend this can also give us the chance to test it better than go live during weekend and found a lot of issues or blockers which need any other contribution from dev team; who will be also unreachable during weekends.

And for the oncall guys, yes we have peter and samir are on call; but this on call is used for emergencies only not for updates, emergency meens website is down or a service is broken and needs immidiate fix.

For last Friday, yes it was an emergency and samir immidiatly jumped in to help and updated the needed links(Thanks @hossnys).

**Comment by xmonader** [comment]
Thank you @Vilnite for offering help during off-hours. I agree that a feature to update/redeploy -at least on staging- is needed and the workflow should be simpler. I don't think updating a link or editing a page and reflecting these changes -at least on staging- should require the operations team or to be classified as an emergency

**Comment by Vilnite** [comment]
As long as someone can step in and take care of urgent updates off hours it's fine.
Also Promotion team is aware that urgent updates include really broken stuff that kills user experience. Rest should be planned and scheduled.
