### ISSUE TITLE
Speed of our websites

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#195]
We are getting feedback that our websites are loading very slowly, especially where internet is rather slow.

Can we please take a look and see what can be done to improve the speed?

**Comment by Hamdy** [comment]
- [] Remove `flexsearch` plugin from all websites from `gridsome.config.js` @samaradel 
- [] Review size of all images and svg files and compress if needed, max size should not exceed 300k or 200k if possible or may be smaller if we can as we have lots of images @ehab-hassan

**Comment by ehab-hassan** [comment]
done all big images resized max-mam size 500k to keep resolution good for some images
