### ISSUE TITLE
Matomo analytics for wiki pages

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#196]
Can we please apply analytics so that each page on wikis is being traced?
Right now we see traffic going to wikis but we can't tell which pages are being looked at.

**Comment by nbabenko** [comment]
<img width="1036" alt="Screenshot 2021-06-11 at 16 35 12" src="https://user-images.githubusercontent.com/4426772/121694691-01151080-cad3-11eb-9433-f2bfa228631e.png">

**Comment by nbabenko** [comment]
- [ ] We need to be able to see each wiki page in the "Pages" section separately
- [ ] Also, if possible we need to see "Site Search" section integrated with the search box of the wiki to track what kind of requests people are searching in the wiki

**Comment by Hamdy** [comment]
for the 1st one : guess this is what u mean? https://developer.matomo.org/guides/spa-tracking
for the 2nd one: I'll see if it is possible, but usually you should have in the dashboard a way to customize what do u want to search  and based on your customizations, u can just give me the final javscript snippet @nbabenko

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/us/8?kanban-status=1609
