### ISSUE TITLE
farming info needs to be update to channel ASAP

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#199]
## Update 1:

# Introducing Certified Farming for a More Secure ThreeFold Grid

Last month, we went live with Titan V2.1, and we're thrilled to count +1,000 orders already from all over the world.

While orders keep on coming, we are happy to launch the Certified Farming Program. Certification brings more security to 3Nodes and hence to the ThreeFold Grid, while also providing more Farming Rewards to Farmers. 

## More Security For Everyone

While anyone can connect hardware to the ThreeFold Grid, some workloads require the highest level of security standards. Certified hardware can only be booted by Zero-OS and allows for 100% tamper-proof capacity. With certification, ThreeFold is pushing the limits further and creating a new global standard for hardware security.

There are many benefits for Farmers to certify their capacity: 

- Get a certified capacity label: Some developers and enterprises will seek for the highest levels of security. With the certified label, you will be able to provide capacity for their workloads at a higher price. 
- Improved hardware security: While DIY farming already provides incredible security, certified farming is 100% tamper-proof. With more security, you bring more security to the ThreeFold Grid and people using it. 

We're building a more secure future for our digital lives. This will happen! 

# Update 2
## Introducing New Farming Rewards.

With the fore-coming launch of the ThreeFold Grid 3.0 later this year, the world is about to go peer-to-peer. With many use-cases to be announced soon, we updated the Farming Rewards to incentivize Farmers to expand the ThreeFold Grid further across the world.

#### New Farming Logic - Introducing Network Rewards

The new Farming Rewards logic can be found in [here](https://threefold.io/info/threefold#/threefold__farming_reward).

You will see that the farming rewards were simplified, and are now calculated according to the compute and storage units provided to the ThreeFold Grid. 

Also, as of this summer, Farmers will also be able to earn more TFT for the Network traffic happening on their 3Nodes. The amount of data coming in and out of their CU and SU will determine extra rewards in the form of Network Units (NU).

- Certified NU: 0.3 TFT per GB per month.
- DIY NU: 0.2 TFT per GB per month.

#### How do I get Certified?
All 3Nodes bought from ThreeFold after June 1 2021 are eligible for certified farming. 
We will send instructions to everyone that purchased a Titan v2.1 on how to upgrade to a certified 3Node next week. 

For people that already bought an earlier batch of nodes, we are thinking of a solution to become certified as our hardware partners need the physical 3Node to certify the hardware.

#### Important notes
- All certified hardware is 100% dedicated to the ThreeFold Grid. While DIY nodes can be booted with a different Operating System, this is not possible with a Certified 3Node.
- All certified hardware is automatically subject to the 3.0 Farming Logic. Read more here: https://wiki.threefold.io/#/threefold__farming_logic3

# Update 3: 
## 40% more income from cultivation if you sell yourself

Another point that was raised within recent conversations was that the cultivation rewards could be improved for the Farmers. The current cultivation reward incentivizes the Sales Channels to promote the usage of the ThreeFold Grid. 

We did this to create a decentralized business model based on selling capacity. So it important to understand that if the Farmer would sell their capacity directly, they would earn for sales of their capacity. 

- A farmer who does not sell capacity (3.0 model) gets 10% of cultivation.
- A farmer who does sell capacity gets 40% extra, i.e. 50% of the total fee.

For instance, a company could reach out to multiple farmers to do active sales for them and in return, they would get 40% of all cultivated tokens. This is ideal for the more "passive" farmers that only want to farm. 

This provides farmers with a very good model to do their own active sales, improving their cultivation returns by 5X (from 10% to 50%). To see what this would mean please set Cell C-20 at 10% and 50% on the ThreeFold Farming calculator.
	
## Exclusive News
With the success of the Titan v2.1, we are creating new powerful 3Node options. To be announced soon.
The new 3Node option will come with much more performance and cost about € 2000.

**Comment by VonSub** [comment]
We can't commit to V2 certification. those ship in 2 to 4 weeks.

**Comment by VonSub** [comment]
@despiegk how do we handle this part:

For people that already bought an earlier batch of 3Nodes, we will automatically consider you Certified if the 3.0 farming rules are accepted. 

^
It's unfair to leave the early adopters out of the increase. It's at max 200 nodes. I think we need to eat that cost to be honest. Just call them different. "Early adopter nodes" or something as they don't have the benefits for the user, but they do deserve the increase.

**Comment by VonSub** [comment]
```
## need everyone to agree on new T&C

- no ability to cancel if they accept new terms
- ...
```

Is this regarding orders? We can't do that. By law people in EU are for instance protected up until 14 after they recieve the node. So even if we ship them, they can still return it within 14, and there's nothing we can do about it.

**Comment by down2basics** [comment]
> @despiegk how do we handle this part:
> 
> For people that already bought an earlier batch of 3Nodes, we will automatically consider you Certified if the 3.0 farming rules are accepted.
> 
> ^
> It's unfair to leave the early adopters out of the increase. It's at max 200 nodes. I think we need to eat that cost to be honest. Just call them different. "Early adopter nodes" or something as they don't have the benefits for the user, but they do deserve the increase.

Add to his that in the future when we have a Certification centre near them they will be informed and they have to get their node Certified (We can provide a 3 to 6 Month time for Certification once we inform them).

**Comment by VonSub** [comment]
> > @despiegk how do we handle this part:
> > For people that already bought an earlier batch of 3Nodes, we will automatically consider you Certified if the 3.0 farming rules are accepted.
> > ^
> > It's unfair to leave the early adopters out of the increase. It's at max 200 nodes. I think we need to eat that cost to be honest. Just call them different. "Early adopter nodes" or something as they don't have the benefits for the user, but they do deserve the increase.
> 
> Add to his that in the future when we have a Certification center near them they will be informed and they have to get their node Certified (We can provide a 3 to 6 Month time for Certification once we inform them).

Added this part. Ok to post tomorrow without the return policy changes @despiegk ?

**Comment by VonSub** [comment]
Update 1 will be posted today.

**Comment by VonSub** [comment]
All posts are ready to go (still need to push, but  I have them all on machine)

**Comment by VonSub** [comment]
1 posted. 2 in the backlog to be posted today/tomorrow. closing issue.
