### ISSUE TITLE
enable bettertoken

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#20]
- [x] enable wiki & website on github: https://github.com/bettertoken (who owns the account, see other issue)
- [x] make wiki & website(s) are automatically published on our web infrastructure (zos based)
- [x] for website make sure source of mobirise is there
- [x] for website make sure its in mobirise (if not let someone convert it quickly)
- [x] make sure gitea account in docs.grid.tf exists & give despiegk, nickolay, ... access
- [x] define milestones 1.0.0 & 1.0.1 and 1.1.0 on all repo's
- [x] apply labels like in threefold (ask reem to help)
- [x] make sure link documented in https://github.com/threefoldfoundation/home/edit/master/README.md

**Comment by VonSub** [comment]
https://docs.grid.tf/bettertoken

**Comment by VonSub** [comment]
@despiegk you mean just the front page to mobirise I guess? the whole page is Wordpress now and hosted in Germany at a company called SaaS web...

**Comment by VonSub** [comment]
converted the page to mobirise, shop will be still linked to the wordpress.

**Comment by VonSub** [comment]
will strip down the wordpress to only the shop environment

**Comment by VonSub** [comment]
BetterToken Mobirise page: https://github.com/BetterToken/www_bettertoken.com

**Comment by VonSub** [comment]
" for website document passwd on the gitea repo" 

@despiegk is this referring to the wordpress?

**Comment by VonSub** [comment]
Bettertoken will be setup tomorrow with the help of @mrconflict

www2.bettertoken.com = already hosted on OVH node ready to replace the current wordpress landingpage.

as stated before, for now shop part will remain on Saas web untill we have new shop definitions.

**Comment by VonSub** [comment]
@rkhamis would you be so kind to instate the milestones on all repo's?

**Comment by VonSub** [comment]
awaiting @arahmanhamdy for wiki setup

**Comment by VonSub** [comment]
@despiegk are you still building something for the wikis to be deployed more easily. This is still waiting for a Wiki for BetterToken.

**Comment by nbabenko** [comment]
Created a separate task for wiki, closing this task
