### ISSUE TITLE
Farming calculator

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/home#200]
- The current one exists here https://secure.threefold.me/sheet/#/2/sheet/edit/uK732tboCu3GY0G7m1fJppi9/
- Manual to use it https://threefold.io/info/threefold#/threefold__farming_calculator

![image](https://user-images.githubusercontent.com/64129/124757305-b6e64a00-df2d-11eb-899b-85d8ee660d74.png)

The plan is to provide 3 alternative calculators with some sort of a more decent interface e.g a small vue page 

Suggestion:

![image](https://user-images.githubusercontent.com/64129/124760547-2447aa00-df31-11eb-962e-61e0aff5b0b6.png)

- [ ] work with markdown and basic TF branding (style, colours)
- [ ] aiming to add this updated calculator to main wiki at first
- [ ] see current calculator's excel sheet to get all input (question) fields (in red) / for all 3 calculators
- [ ] output (for all) = ROI %

**Comment by ehab-hassan** [comment]
![calculator1](https://user-images.githubusercontent.com/10484295/125605751-e3b707c8-c31a-4065-8b19-e447f3281897.png)
I made layout for farming calculator It ll be tabs ( Calculator Certified and DIY Certified )
and calculate CU & SU ll be at right all the time

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/35
