### ISSUE TITLE
Forum facelift and improved user flow

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#201]
Currently our Forum is still not super appealing and user flow is not smooth enough.

- [x] explore possibilities of the forum tool and do a facelift
- [ ] Improve user flow organising content in clear categories and sub-categories (@Sacha96)

See examples such as Cardano Forum: https://forum.cardano.org/

<img width="1440" alt="Screenshot 2021-07-14 at 09 47 41" src="https://user-images.githubusercontent.com/20182572/125576186-0311c5ad-40b9-42e4-9ec4-4e581cd40445.png">

**Comment by Vilnite** [comment]
Suggested changes regards look of our forum:

<img width="1439" alt="forum 18 52 44" src="https://user-images.githubusercontent.com/20182572/125575500-6658a433-1dca-4171-a344-adc8af5b5ea0.png">

**Comment by Sacha96** [comment]
super cool stuff @Vilnite!

let's share this with stakeholders and see how to re-orgnanize forum topics and how to share change with community as next stories :)

**Comment by Vilnite** [comment]
Moved to Operations team's circle: https://circles.threefold.me/project/team_operations/us/162
