### ISSUE TITLE
Push FreeFlow Wiki 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/home#204]
Description: 
FreeFlow Wiki need to be pushed at the end of the week. 

FreeFlow Wiki repo: https://github.com/myfreeflow/info_freeflow/issues/1

Invited the web dev team members to join the respective repos. 

Issue on Info_freeflow: https://github.com/myfreeflow/info_freeflow/issues/1

End: 
When the wiki has been pushed.

Deadline: 
1st August 2021

**Comment by hossnys** [comment]
- there is no provided info about which domain to use for this wiki ?
- is this request one step forward to production or need to go staging for review then go production ?

**Comment by AlexandreHannelas** [comment]
Domain: myfreeflow.org
Wiki link: info.myfreeflow.org

**Comment by hossnys** [comment]
done and live now :

staging on : https://staging.threefold.io/info/freeflow#/
production on : https://www.info.myfreeflow.org/#/ & https://info.myfreeflow.org/#/
