### ISSUE TITLE
Forum login fails when email address doesn't match Connect app

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/home#205]
I am currently unable to log into the TF [forum](forum.threefold.io). After completing login the steps in Connect app, I still see the login button rather than my avatar.

Tested on, with same result:
Linux - Brave, Firefox, Opera
Windows - Brave, Edge

My main system has an open and functioning session, so I don't need direct support. Others may be unable to post.

**Comment by sabrinasadik** [comment]
@hossnys can you take a look at this?

**Comment by hossnys** [comment]
see the mail is different , it seems that you logged out from your threebot login account on phone and changed the used mail or changed the mail on forum account you need to make them the same

![Screenshot from 2021-08-02 18-47-12](https://user-images.githubusercontent.com/26298009/127896619-f3706982-c726-4700-ba2a-9ab9f2d7db92.png)

![Screenshot from 2021-08-02 18-52-16](https://user-images.githubusercontent.com/26298009/127896730-d0cfc49f-6b4e-4066-8586-839796d2124f.png)

**Comment by hossnys** [comment]
@scottyeager please verify and ping me if still have issue or close issue if solved

**Comment by scottyeager** [comment]
Thanks @hossnys, I am understanding the issue now. A few opportunities I see here:

1. Warn the user when they update their email address in the forum, that they will be unable to login if it doesn't match the app
2. Display an error when login fails for this reason, advise user they'll have to change email in app if they aren't still logged into the forum somewhere to be able to change it there
3. Disconnect forum email from app email altogether. That is, can we just authenticate users based on their 3Bot name in app, rather than needing to match email too?

**Comment by despiegk** [comment]
this is reported long time ago, but we did not follow up
it came again with the board, we need to look into this

**Comment by sabrinasadik** [comment]
We need to make sure that for all our platforms (forum, circles,..) we make sure that the TF Connect app username is used as a verification, not email address.

**Comment by sasha-astiadi** [comment]
still an issue? @sabrinasadik @hossnys

**Comment by scottyeager** [comment]
Yes, I'm stilling examples of this happening to users on the forum.

**Comment by sasha-astiadi** [comment]
@hossnys please take a look again

**Comment by hossnys** [comment]
This issue need to be fixed by dev team to change the threebot login procedure to just depend on the threebot name not the mail in threebot account as fixed before in circles ( taiga ) .

**Comment by sasha-astiadi** [comment]
@rkhamis does this fall on your end or jimber end? cc: hossny's comment above

**Comment by sasha-astiadi** [comment]
is this still a problem @scottyeager
