### ISSUE TITLE
Create an Open Position template

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#206]
- [x] Core company values
- [x] Role & Location
- [x] Description of the role
- [ ] Team details
- [x] Requirements (specific skill set, knowledge, experience or training required for the job)
- [x] Skills (qualities that are nice to have and would be seen as an added advantage)
- [ ] Remuneration - Industry Pay? (for our own knowledge and budgeting)
- [x] Benefits we offer

Here's the doc for [Open Position Template](https://secure.threefold.me/pad/#/2/pad/edit/d20wrF0WtSHZ5r1er1txSFIb/)

**Comment by Sacha96** [comment]
QUALITY ASSURANCE ENGINEER

We are looking for a detail-oriented individual to join our Engineering department as a Quality Engineer. You will be primarily responsible for checking and managing the quality standards of the development process. You will also be responsible for maintaining the quality control systems and ensuring that all processes adhere to production quality standards.

As a Quality Engineer, you should be able to prepare and implement the quality control guidelines. Besides, you should also be able to identify any problems in the production process and suggest improvements. You should be able to prepare detailed and accurate reports on the development findings.

To excel in this job role, you will have a complete onboarding on our quality processes, tools, and code. Ideally, you should hold a valid QA certification and have relevant experience in the Engineering department. Furthermore, you should display strong analytical and problem-solving abilities. Your ability to handle stressful situations will be advantageous.

Values & Passion:

Understand what it means to work in a growing agile project and ecosystem.
Resonate with our values & collaboration manifesto (2017).
Be passionate and willing to bring a positive change in our world.
Understand it won't be a 9-5 job. We are changing the world, it takes courage and perseverance.
Be willing to travel and to other locations for to work directly with our global team.

Role:

The ThreeFold Grid will eventually have millions of nodes, and it’s very important to develop an extensive QA program. Our components are low level and requires highly technical people to overlook the push from testnet to production. We are looking for a QA Engineer who will take ownership on the overall testing of both the low level technology components of the ThreeFold Grid primitives and applications built on top of it.

Your main responsibility will be to test the code behind the ThreeFold Grid and making sure that it adheres to the highest possible quality through testing scenarios, test cases and executing upon findings. Also building a new Internet involves educating the world on how it works, so documentation will be a crucial part of your process too.

Test our latest technologies end-to-end.
Test in an agile project setup.
Develop and execute exploratory and automated tests to ensure product quality.
Work in our international team.
Be an ambasador of our ethos, why we do what we do, and why we will make it happen.
We are working on:

A peer-to-peer operating system
A peer-to-peer virtual system administrator
Blockchain technology
Smart Contract for IT
Skills

Personal skills:

Able to question the status quo
Out-of-the-box thinking
Smart & agile
Fast learner
Technical skills:

Able to think conceptually about data models, IT architecture and business requirements
Fluent with github and agile processes
Proven work experience in software quality assurance
Technically skilled to understand how a cloud should work from a user perspective
Professional skills:

Fluent in English
Good communicator, also in an international environment
Understand and able to work according to Pareto 20/80 rule
Able to be a servant leader to others
Flexible out of the box thinker (everything you will be working on is based on new paradigms)
Don’t be afraid of changes
Understand that quality is important

What we offer:

A desk in our Belgian office
A competitive wage
Flexible hours
Great team spirit
Yearly team trips abroad

**Comment by Sacha96** [comment]
So Peter said competitive wage is enough for wage & team description depends on team owner...

**Comment by Sacha96** [comment]
https://secure.threefold.me/pad/#/2/pad/edit/Rc5SDsWLQrMqZm4EmBWc7EVh/ for QA Engineer

**Comment by Sacha96** [comment]
https://secure.threefold.me/pad/#/2/pad/edit/jMB3LDwhPth5suPQtrITzT3s/ for senior developer

**Comment by Sacha96** [comment]
https://secure.threefold.me/pad/#/2/pad/edit/whRV36ltsgpGkQoG1sOmpq+j/ for master technical architect

**Comment by Sacha96** [comment]
https://secure.threefold.me/pad/#/2/pad/edit/8eaTyvrT1Ss3nil9VzGUNsHc/ for Grid operations lead @andhartl

**Comment by Sacha96** [comment]
https://secure.threefold.me/pad/#/2/pad/edit/ONdt99buKtztxseeDq-22XVi/ for Grid Dev Lead @despiegk

**Comment by down2basics** [comment]
Have made some changes to the above documents. Mostly Spelling mistake corrections.

**Comment by Sacha96** [comment]
https://secure.threefold.me/pad/#/2/pad/edit/jEYhergIb1zbN8fRp5gDCSsc/ for operations of hrdware and sales @andhartl

**Comment by Sacha96** [comment]
Thanks @down2basics! @Vilnite can you pass all of them through grammarly before adding on gitpod? or should i?

**Comment by Vilnite** [comment]
I'm on it.

**Comment by Vilnite** [comment]
Template for open positions: https://secure.threefold.me/pad/#/2/pad/edit/d20wrF0WtSHZ5r1er1txSFIb/
