### ISSUE TITLE
Put in writing hiring process

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#207]
Here's a doc where I've added as much as I can: https://secure.threefold.me/pad/#/2/pad/edit/YyE5y+BkXYNir29Sk2291UWA/
Please @Sacha96 improve where/if you find necessary.

@sabrinasadik is off and won't be able to help here, I've asked @down2basics and Peter to look at it.

**Comment by down2basics** [comment]
The hiring process is fine for version one, we can keep improving the process as we go along. For now, we should be good to go.
