### ISSUE TITLE
enable costa rica project

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#21]
## organic farming project costa rica

- virtual company for now
- uses TFT to sell products
- ... to complete

## goal

- create a virtual team which will manage this project
- put in place the basic infrastructure
- put basic first info in place (can be very small to start with)

## deliverables 

- [x] choose name usable for github,name.com 
- [x] ask kristof to register name in name.com (so its in right account)
- [x] create github account (access to despiegk, nbabenko, ...), ask Kristof to create !
- [x] create docs.grid.tf account (access to despiegk, nbabenko, ...)
- [x] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [ ] make sure website & wiki are on our publishing platform exposed (production,staging)
- [x] create space on freeflowpages
- [x] create dir in gdrive on tf extranet, create homepage

## requirements

- < 2 days work !!!
- its just a starting point so we can build team

**Comment by juradoo** [comment]
The farm is located in Biolley, Costa Rica and it is called Finca Biolley

**Comment by juradoo** [comment]
Project Name: Cultivo

**Comment by nbabenko** [comment]
https://docs.google.com/document/d/1c3wklPZQx5GUrAA15oxrBA7f8iOSSO7dPsjr3M4Xock/edit

**Comment by juradoo** [comment]
https://github.com/cultivo
