### ISSUE TITLE
Convert Incubaid website to Gridsome

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#211]
If we want to work on Incubaid website it needs to be brought on Gridsome so it's compatible with Publishtools.
This requires recreation of current website using our web stack.

See issue: https://github.com/Incubaid/www_incubaid/issues/32

Need stakeholders approval.

**Comment by xmonader** [comment]
For now the current content can be served using caddy or any kind of webserver to bring that website up again if not resolved already

**Comment by Vilnite** [comment]
Added to circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/33
