### ISSUE TITLE
Cannot log in to forum.threefold.com

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/home#218]
Trying to post an article on the forum and I am not able to log in.

URL: forum.threefold.io
3bot name: weynandkuijpers

**Comment by delandtj** [comment]
.com .me.... .io maybe ?

**Comment by weynandkuijpers** [comment]
no. My bad. it was the .io domain - but when I log in and use TF Connect I do log in - I go back to the login screen.

**Comment by weynandkuijpers** [comment]
Changed to firefox and now i works.....  Weird.  will close the issue and see if it resurfaces.
