### ISSUE TITLE
choose ticketing solution

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#22]
e.g. https://www.opensourcecms.com/osticket/

## criteria

- opensource
- php or python or golang or rust
- needs to be able to change data backend to talk to 3bot in future
- can integrate with IYO
- can integrate with TF crm system ? https://docs.grid.tf/threefold/itenv_www_crm
- can deploy on TF grid
- can setup multi org or multi project so we can distinguish between TFTech support vs VEDA support etc etc
- well documented on github
- mobile app available
- able to integrate with TF wallet app ?
- brandable by project/org ?
- external customers/users can login and track tickets progress ?

## features

- api or easy to create api

## todo

- install demo
- review with kristof, chris, ramez, andreas, ...

## where will we use

- tickets for TFGrid, VedaOnline, many other projects coming
- each project will have its ticketing system

**Comment by Hamdy** [comment]
Interesting solutions :: https://opensource.com/article/18/2/agile-project-management-tools
I personally find Taiga is very good candidate (python/Django + Angular for front end) + neat documentation 
and totally open source

Coordinating with Samir to these ones before we take final decision 
```
Taiga
OpenProject
Tuleap
```

**Comment by christopherhutton** [comment]
@Hamdy im not sure you are looking into the right tools? We need a ticketing system..not project management ?

**Comment by ramezsaeed** [comment]
@despiegk @christopherhutton 
- so we need a ticketing system which will be only used by the customers
- not a system for internal use for our tasks and follow up the projects details
right ?

**Comment by christopherhutton** [comment]
> @despiegk @christopherhutton
> 
> * so we need a ticketing system which will be only used by the customers
> * not a system for internal use for our tasks and follow up the projects details
>   right ?

for me, the requirement is for a support ticketing system... customers will log support tickets on us and we will use the same system to manage the tickets until logged issue is resolved

**Comment by Hamdy** [comment]
Based on my discussion with @ramezsaeed  We've come to the following best solutions
 
|  Rating | Name  | Demo  | Github  | Notes  |
|---|---|---|---|---|
|  5 | ZAammad |  [Demo](https://zammad.org/screenshots) |  [Github](https://github.com/zammad/zammad) |ruby,ubuntu installers, dockers, rest API, good   |
| 4  |Faveo  |[Demo](https://www.faveohelpdesk.com/online-demo/)   |  [Github](https://github.com/ladybirdweb/faveo-helpdesk)  | php, API rest, ios, android, docker, knowledgebase  |
|  3 | Helpy  |  [Demo](https://demo.helpy.io/en) |  [Github](https://github.com/helpyio/helpy)  | ruby,API, mobile friendly, knowledgebase  |
|  3 |  opensupport | [Demo](https://www.opensupports.com/demo/)  |  [Github](https://github.com/opensupports/opensupports)  |  php, api|

Also as a side project not practical in this case but @despiegk might like
http://github.com/schacon/ticgit which is a ticketing system management through git

**Comment by hossnys** [comment]
you can login to a Zammad [Demo](http://10.102.191.143) and register a new user , you will get verification mail in spam to verify your account.

**Comment by hossnys** [comment]
Faveo system installed [here](http://10.102.90.219:8181/)

admin / adminadmin

**Comment by hossnys** [comment]
Faveo installed on ThreeFold Production Server Farm [Here](http://10.102.90.219:8282)
login :
 admin / adminadmin

**Comment by hossnys** [comment]
update:
Faveo (Threefold Support) installed on a container in ThreeFold Production Server [Here](https://support.grid.tf) after rebranding and waiting for 3bot login to be integrated there .
login :
admin / rooter

**Comment by zgorizzo69** [comment]
It could be nice also to have an integration with github so that 
* we can easily create an issue based on a ticket
* a ticket can automatically be closed based on the close status of an issue
* track the work that has been done on a ticket and who is assign to it
