### ISSUE TITLE
update veda website to its latest content

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#222]
- [x]  get emre into veda-websites organization as admin
- [x] go to [www_veda-egypt_com](https://github.com/veda-websites/www_veda-egypt_com) and download it into local computer
- [x] update the veda website mobirise file and save it
- [x] ehab introduce how to use mobirise 
- [x] put the updated file into the www_veda-egypt_com folder on your local computer
- [x]  push it online

**Comment by ehab-hassan** [comment]
done by @PeterNashaat
