### ISSUE TITLE
update relevant companies on the incubaid website

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#223]
remove irrelevant companies from the incubaid website and add all the currently relevant ones

currently relevant companies:

- [x] TAG
- [x] OurVerse
- [x] ThreeFold
- [x] BETTERTOKEN
- [x] MAZRAA
- [x] OurWorld
- [x] Sikana
- [x] Ootopia

**Comment by sasha-astiadi** [comment]
updated and livw? @remrekoc

**Comment by sasha-astiadi** [comment]
contact webcore and tell them to rebuild it on staging, ask them to teach you how to build it on stagin

**Comment by despiegk** [comment]
where is this work?

**Comment by remrekoc** [comment]
Updated and live

**Comment by sasha-astiadi** [comment]
https://github.com/Incubaid/www_incubaid/commit/7cd017ae7309b580d684b0e94f69b0c9113c73d2
