### ISSUE TITLE
create specs for personal 3bot kanban

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#23]
# idea

- in 3bot using vue.js & gedis backend allow user to see kanbans for tasks, tickets

# requirements

- integrate with a chosen ticketing system (see  #22 )
- integrate with issues on github & docs.grid.tf
- integrate with tasks / assigned comments on gdrive
- integrate with trello
- integrate with tasks on humhub (freeflow pages)
- as person need to be able to define which github accounts, docs accounts, ... I am involved with
- needs to give unified view
- deal with labels (e.g. story_ fs bug_...)
- shows milestones or deadlines (depending chosen system)
- easy to search
- support multiple kanbans where query criteria can be set
- support from kosmos shell

# goal of tool

- show all tasks, issues, ... which are related to me as person on all projects I am working with

# how will it be implemented

- through our bounty program on threefold
- the gedis in background will fetch the tasks/issues/... and store in local BCDB so querying goes fast
- the tasks/... will not be changed from 3bot perspective, but link to source is shown, so user can edit there

**Comment by Sacha96** [comment]
@despiegk is this still relevant in regards to 3bot progress?
