### ISSUE TITLE
Table of content Links on FAQ https://library.threefold.me/info/manual/#/manual__faq get 404 Not found 

### ISSUE THREAD

**Issue by buchmann** [threefoldfoundation/home#230]
https://library.threefold.me/info/manual/#/manual__faq
Wrong Links : 
content links example : [What is the the Threefold blockchain?](https://library.threefold.me/info/manual#what-is-the-the-threefold-blockchain) -> get 404 
The link should go to:  [What is the the Threefold blockchain?](https://library.threefold.me/info/manual#/manual__faq?id=what-is-the-the-threefold-blockchain)
https://library.threefold.me/info/manual#

All new content links should go to https://library.threefold.me/info/manual#/manual__faq?id=   instead of https://library.threefold.me/info/manual#

**Comment by sasha-astiadi** [comment]
fixed , all links working
