### ISSUE TITLE
enable bulk storage capacity provider

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#24]
## bulk storage capacity provider

- virtual company
- uses TFT to sell products
- products 100,250,1000 TB wholesales storage at very cost effective pricing schemes
    - 5-4-3 $ per TB per month (SU at 16-4 schema, but netto usable)
- will do back2back agreements with TF Farmers
- very simple value prop

## goal

- create a virtual team which will manage our "bulk storage capacity provider"
- put in place the basic infrastructure
- basic first content (can be small, just to get started)

## deliverables 
- [x] choose name usable for github,name.com 
- [x] ask kristof to register name in name.com (so its in right account)
- [x] create github account (access to despiegk, nbabenko, ...), ask Kristof to create !
- [x] create docs.grid.tf account (access to despiegk, nbabenko, ...)
- [x] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [x] make sure website is on our publishing platform 
- [x] make sure wiki is on our publishing platform
- [x] create space on freeflowpages
- [x] create dir in gdrive on tf extranet, create homepage

**Comment by VonSub** [comment]
(SU at 16-4 schema, but netto usable) @despiegk could you elaborate on that, I'm not following this.

**Comment by VonSub** [comment]
for now project name: harvested.io

**Comment by VonSub** [comment]
Harvested.io bought on name.com

**Comment by VonSub** [comment]
https://docs.grid.tf/org/Harvested.io

**Comment by VonSub** [comment]
https://github.com/harvested-io

**Comment by VonSub** [comment]
https://drive.google.com/drive/u/1/folders/1xilMwXH0-PW0lTd91lymYciCpSvPCGTy

**Comment by VonSub** [comment]
www2.harvested.io and www.harveste.io are live. Wiki's are blocked.

**Comment by VonSub** [comment]
awaiting @arahmanhamdy for wiki setup

**Comment by VonSub** [comment]
Repo is ready for wiki, but does this project need a wiki already?

**Comment by VonSub** [comment]
https://github.com/harvested-io/info_harvested.io/issues/1#issuecomment-501624134
