### ISSUE TITLE
build mastodon website

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#248]
- [x] design by zia https://xd.adobe.com/view/2a59b851-fd90-456c-981b-401741ff30cd-7f0a/?fullscreen
- [x] images in gdrive
- [x] repo [www_mastodon](https://github.com/threefoldfoundation/www_mastodon) - cloned from www_ournomads, edit content
- [x] build on zola
- [x] ask ops to deploy on mastodon.threefold.io

**Comment by sabrinasadik** [comment]
- White empty header and footer blocking a big section after accepting cookies.

**Comment by sabrinasadik** [comment]
- It's Mastodon, not Mastadon
![Screenshot 2022-11-14 at 15 24 05](https://user-images.githubusercontent.com/31733464/201684418-b4cc7b7c-f963-46d7-a315-d25d52a73142.png)

**Comment by sabrinasadik** [comment]
Again, Mastodon
![Screenshot 2022-11-14 at 15 26 26](https://user-images.githubusercontent.com/31733464/201684893-bac10d7d-d518-4c9f-b5a1-78c842e6c950.png)

**Comment by sabrinasadik** [comment]
Safer Log in options
![Screenshot 2022-11-14 at 15 27 47](https://user-images.githubusercontent.com/31733464/201685240-a61bebd0-e77e-40ab-b9ba-b3480af49b7c.png)

**Comment by sasha-astiadi** [comment]
thanks sabrina, we're aware of the mastodon typo, but other ones appreciated

**Comment by sabrinasadik** [comment]
Quickly & quick?
![Screenshot 2022-11-14 at 15 28 46](https://user-images.githubusercontent.com/31733464/201685479-29e8987e-c3b4-4c45-af10-64c308a54f92.png)

**Comment by sabrinasadik** [comment]
Why the # ? Not making sense to me... 
![Screenshot 2022-11-14 at 15 30 12](https://user-images.githubusercontent.com/31733464/201685821-775c45b1-7639-44cd-9c5a-a9cc847ff191.png)

**Comment by sabrinasadik** [comment]
I'd say without any additional cost or support cost, because right now it says 'buyers' and 'without any cost'

![Screenshot 2022-11-14 at 15 31 28](https://user-images.githubusercontent.com/31733464/201686167-9311b888-8d90-4b67-b6f5-1d605d210e04.png)

**Comment by samtaggart** [comment]
Hi there, looking good. A couple notes:

1. I would propose we somewhere invite people to join the discussion and link to the Fediverse category on the ThreeFold Forum.
2. We might want to consider also a button somewhere that links to this forum topic specifically (https://forum.threefold.io/t/mastodon-threefold-101-what-is-mastodon-and-how-can-threefold-support/3494) which kind of summarizes how Mastodon and ThreeFold work together.

**Comment by samtaggart** [comment]
> I'd say without any additional cost or support cost, because right now it says 'buyers' and 'without any cost'
> 
> ![Screenshot 2022-11-14 at 15 31 28](https://user-images.githubusercontent.com/31733464/201686167-9311b888-8d90-4b67-b6f5-1d605d210e04.png)

Agree this is confusing ... Wouldn't it be "The first people to reserve ..." if it's free?

**Comment by samtaggart** [comment]
> Why the # ? Not making sense to me... ![Screenshot 2022-11-14 at 15 30 12](https://user-images.githubusercontent.com/31733464/201685821-775c45b1-7639-44cd-9c5a-a9cc847ff191.png)

Also ThreeFold does not have an official Mastodon channel. Are we talking about a server or an account on Mastodon?

**Comment by sasha-astiadi** [comment]
Will answer your question on a new issue linked here
