### ISSUE TITLE
Make a new www_examplezola for our future websites

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#249]
Make a new www_examplezola for our future websites

- [x] clone from ournomads
- [x] remove the ournomads stuff so it wont confuse ppl
- [x] make sure its not linking to any domain
- [x] add this repo to our home readme... "to build a new website, please use this repo"

**Comment by ehab-hassan** [comment]
all done and responsive.
https://github.com/threefoldfoundation/www_examplezola
![image](https://user-images.githubusercontent.com/10484295/201955154-61d39412-ffdc-48bb-8c5e-6434ad0bbf20.png)
