### ISSUE TITLE
enable 3bot project

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#25]
## give form to 3bot project

- your digital avatar online
- uses TFT to sell service
- needs to be in line with https://digindec.com/ (will be kind of starting point, see andrew)
- need to get market message right
- will be starting point to how to use the grid, you will need this to be able to use anything on our grid

## goal

- create a virtual team which will manage this project
- put in place the basic infrastructure
- put basic first info in place (can be very small to start with)

## Deliverables 

- [x] choose name usable for github,name.com  (maybe 3bot is too techy)
- [ ] ask kristof to register name in name.com (so its in right account)
- [x] create github account (access to despiegk, nbabenko, ...), ask Kristof to create !
- [x] create docs.grid.tf account (access to despiegk, nbabenko, ...)
- [x] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [ ] make sure website & wiki are on our publishing platform exposed (production,staging)
- [x] create space on freeflowpages
- [x] create dir in gdrive on tf extranet, create homepage

## requirements

- < 5 man days work !!!
- its just a starting point so we can build team & go from there

**Comment by despiegk** [comment]
about the declaration

- now its too legal, needs to still become softer
- needs to have some more content to do with grid & new 3bot
- needs to be the start of a new free digital world

**Comment by nbabenko** [comment]
We have all parts ready but with 3bot name. 

@AdnanFatayerji , can you please help to brainstorm new name?

**Comment by juradoo** [comment]
Do we need new name + new image for the bot or only new name? @nbabenko @despiegk @AdnanFatayerji

**Comment by Sacha96** [comment]
@nbabenko @juradoo @AdnanFatayerji any updates regarding the above? I'll take over from there. Regards.

**Comment by AdnanFatayerji** [comment]
@Sacha96 I know @juradoo  is working on updating the 3bot wiki, please coordinate with her, i see the checklist is still pending.

**Comment by Sacha96** [comment]
> @Sacha96 I know @juradoo is working on updating the 3bot wiki, please coordinate with her, i see the checklist is still pending.

Will do. Thanks @AdnanFatayerji.

**Comment by juradoo** [comment]
@nbabenko @VonSub Regarding Deliverables listed above, I cannot find 3bot  dir in gdrive on tf extranet, is there a homepage somewhere else? 

create dir in gdrive on tf extranet, create homepage

**Comment by juradoo** [comment]
3Bot Wiki has been started here for now: https://github.com/threefoldfoundation/3bot/tree/master/docs
