### ISSUE TITLE
Proposals for TFT Community Grants

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#250]
We’ve been talking about creating some TFT grants for tasks that we want to complete but don’t have the time for, and making them public on the forum and potentially github. It would be great to get some recommendations from the team for what some of those grants could be, please respond here so we can discuss.

Please also give a suggestion for amount of TFT. As examples, in the past we have given 500 TFT for video creation, 500 TFT for proactive help on the forum, and 2000 TFT for testing deployments and producing a new Kubernetes flist. Not saying these are right or wrong, but they are reference points.

**Comment by samtaggart** [comment]
We've been discussing Drew's contributions in one of the chats. @scottyeager suggestion which a few of us also agree with:

Drew has made 19 videos that I can count in the gallery, and has done a bunch of testing and also produced some guides and documentation

My feeling is we should pay at least 20,000 TFT as the lump sum and then 5-10k per month ongoing. He also estimates spending $250-300 worth of TFT paying for deployments in testing, which is 12.5-15k TFT at current price

**Comment by sabrinasadik** [comment]
I would suggest adding guidelines to a forum post which include:

- Type of task (video, documentation, testing,...). 
- TFT reward (between x and xxx TFT for every type of task). Leave it up to teammember to decide between this range. 
- Logging tools (where to log or upload. 

Whenever a new task is available, it gets posted on TF chat and first one adding his name to the task, can add wallet address and ETA. Once reviewed, task owner gives OK and tags me so transaction can be created from TF Promotion wallet.

**Comment by Ashishban** [comment]
One suggestion, we might need to limit the number of tasks like only 5 open task in any month or 5 task open until review is done and project is marked complete. So devs can manage their own time and the task we keep in open source.
