### ISSUE TITLE
ourverse - blog wont work

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#254]
<img width="1378" alt="Screenshot 2023-01-02 at 09 43 21" src="https://user-images.githubusercontent.com/43240801/210209615-a5a7c38e-d90b-42d6-8981-de1a6e23b309.png">
i tried to 

i tried chnaging the directory of the image on index.md but wont work. can u see whats wrong?

https://github.com/ourworldtsc/www_ourverse

**Comment by ehab-hassan** [comment]
fixed at production
https://www.ourverse.tf/blog/
