### ISSUE TITLE
ourworld.tf broken

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#259]
please investigate and see what happened
<img width="1400" alt="Screenshot 2023-01-25 at 11 03 57" src="https://user-images.githubusercontent.com/43240801/214471187-6c3183b7-7733-4072-aa7e-c81f482dd0f1.png">

**Comment by ehab-hassan** [comment]
@PeterNashaat I think we need build here to show the tailwind at staging

**Comment by PeterNashaat** [comment]
- Fixed.
