### ISSUE TITLE
Pricing information displays the wrong number

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/home#260]
The could pricing table provides the wrong numbers for network and IP address:
![image](https://user-images.githubusercontent.com/13766992/214516500-9da69566-05a9-422b-b08a-ebbf785db777.png)

It reflect 40% discount, not 60%

I think this is the source file for the table: tfgrid/pricing/cloudunits_pricing.md

**Comment by andhartl** [comment]
the prices seem high and are we sure about the discounts?
