### ISSUE TITLE
proofread all websites

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#262]
https://docs.google.com/spreadsheets/d/1RsCcmXt2ds4wWK-Tdp6KokyoGl-dEW96W84O89eiE4U/edit?usp=sharing

on above link is list of all websites. 
this is an issiue for all the support team members to proofread all the websites. the link contains all the **url of the websites**, and all the **repos link**.

- each team member is assigned to proofread on the document

- find broken links, typo, old information (for example- ex employee being listed on the website, etc), image doesnt look right, please attach screenshot

- create one issue for each website containing all the errors... please just **one issue per website**, not one per error found, **create the issue on the website's repo**. if the website repo is not on TF Foundation org, create the issue on **home repo** (this repo). if no error found, no need to.

- assign the issue to me, and link it to web presence 3.8.1 project, thank you.

- [x] Bettertoken
- [x] TFexplorer
- [x] Incubaid
- [x] Ourverse
- [x] Ourworld
- [x] Redseacat
- [x] ThreeFold
- [x] Veda
- [x] Veda Retreats
- [x] Codescaler
- [x] FreeflowNation
- [x] Mazraa
- [x] GetTFT
- [x] Artheon
- [x] Ourphone
- [x] OurNomad
- [x] OurParadise
- [x] Venture Creator studio
- [x] freeflow twin

**Comment by amandacaster** [comment]
Sure @sasha-astiadi.

**Comment by mahendravarmayadala93** [comment]
Sure @sasha-astiadi

**Comment by Ashishban** [comment]
All websites proofread is complete that have been assigned to me.
