### ISSUE TITLE
Website : OurVerse.tf : Errors found

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/home#263]
Website: https://ourverse.tf/

Respective website repo: https://github.com/ourworld-tsc/www_ourverse/issues

#Home page Errors :

- [x] 1) "Explore" button on the homepage opens a new window redirecting to the URL: https://www2.ourverse.tf%22%22/ which is broken

![image](https://user-images.githubusercontent.com/89931135/217282174-88bf5e9f-a855-4fa9-837e-127f7b749bee.png)

- [x] 2) "Discover the tech" button on the home page leads to the same error as above

- [x] 3) "Email" button at the bottom of the page just reloads the page and not redirecting to any outlook app or to a different page.

- [x] #BLOGS :

Found no issues.

- [x] #USE CASES :

- [x] 1) "Email" button at the bottom of the page redirects to the home page. 

- [x] #TECH

The Tech page is a replica of the home page. There's no difference between these two pages.

- [x] #Get in touch

When I clicked on the "Get in touch" button, for the first time it showed a popup box to select the preferred app to open. When I select "Microsoft outlook" it opened a new email with the "info@ourverse.tf" in the "To" field. But when I select google chrome it just opens up a new window of Google Chrome.

**Comment by sasha-astiadi** [comment]
@mahendravarmayadala93 thanks mahendra, noted :)

**Comment by mahendravarmayadala93** [comment]
@sasha-astiadi You're welcome.
