### ISSUE TITLE
turn cloud.threefold.io into zola framework

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#264]
turn cloud.threefold.io into using zola framework 

 website cloud.threefold.io on repo:
https://github.com/threefoldfoundation/www_threefold_cloud
its a one page website

- [x] make new project www_tfcloud_zola
- [x] copy / paste information from old website
- [x] make sure same logo, color, font style, and layout format
- [x] make sure its mobile responsive correctly
- [x] ask ops to redir cloud.threefold.io to the new website instead of old one
- [x] archive the old website repo, add info: this has been archived on read.me

**Comment by ehab-hassan** [comment]
That is very old website @Sacha96  ask us to create new one 2 years ago with Gridome then we move all cloud content inside io as (build page)
https://www.threefold.io/build/

**Comment by ehab-hassan** [comment]
this is the new repo
https://github.com/threefoldfoundation/www_tfcloud_zola

**Comment by ehab-hassan** [comment]
@sasha-astiadi the old repo will archive here https://github.com/threefoldfoundation/www_archive?

**Comment by ehab-hassan** [comment]
https://www.cloud.threefold.io/

**Comment by sasha-astiadi** [comment]
thank you! works perfectly ehab
