### ISSUE TITLE
veda - fix the contact us button

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/home#265]
Website : https://veda-retreats.com/

Website Repository : https://github.com/ourworld-tsc/www_veda-retreats

Hi Team,

I observed while clicking on the "Ready to recharge yourself" button, it's not taking back to the position where it shows the below image
![image](https://user-images.githubusercontent.com/89931135/218776952-3deb0f28-4637-4555-9e23-a0ea9469761a.png)

Resulting the Button seemed to be not working

Example position :
![image](https://user-images.githubusercontent.com/89931135/218777630-ef52d778-45e6-4620-87f6-71ee4e747db9.png)

At the position, when I click on the button there's a little movement in the page but it's not taking to the position of the first picture in this thread. Kindly check.

**Comment by sasha-astiadi** [comment]
i rewrite this issue into 'contact us button' not working


![Image](https://user-images.githubusercontent.com/43240801/232489388-d8d28f95-e6f5-460d-81ff-2cfcac885229.png)

**Comment by ehab-hassan** [comment]
@sasha-astiadi while this site is static we need to run any form plugin for example (formspree) can store data but the free one is limited with 50 contact I think, Or we can just keep button and linked to Veda mail what do u think?

**Comment by sasha-astiadi** [comment]
i think we can do the same like,
"Contact Us" button, redir them to a new tab, email veda

**Comment by ehab-hassan** [comment]
done all mailto:info@veda-masters.com
