### ISSUE TITLE
Incubaid - Proofread - Errors 

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/home#266]
The Alliance for a Conscious Internet link shows an invalid response when you open it - https://consciousinternet.org/
![image](https://user-images.githubusercontent.com/88147124/220048411-949c8fb6-c675-4cb5-85cb-1d132bea1549.png)

Website- https://incubaid.com/
GitHub repo - https://github.com/Incubaid/www_incubaid

**Comment by sasha-astiadi** [comment]
removed. thanks

**Comment by amandacaster** [comment]
Just checked this as well and the link still seems to be there. 

https://user-images.githubusercontent.com/88147124/220117564-d10efbc1-2d25-4a5a-873a-bf86644d38a4.mp4

**Comment by sasha-astiadi** [comment]
now its live, thanks @amandacaster hope its no longer there

**Comment by amandacaster** [comment]
Just checked and it is not there, Thanks @sasha-astiadi.
