### ISSUE TITLE
Venture Creator studio - Proofread - Errors

### ISSUE THREAD

**Issue by amandacaster** [threefoldfoundation/home#267]
Under the Venture creator About the Contact us button does not go anywhere, 
https://venturecreator.studio/about/
![image](https://user-images.githubusercontent.com/88147124/220051984-e67896c8-53aa-47d9-ad6d-8a4430c0ae16.png)

Website - https://www.venturecreator.studio/
GitHub Repo - https://github.com/threefoldfoundation/www_venturecreator

**Comment by sasha-astiadi** [comment]
it works to send mail to info@threefold.io

**Comment by amandacaster** [comment]
Hey @sasha-astiadi, I just checked and clicked on contact us but there is no pop-up or contact form or anywhere it takes us. 

https://user-images.githubusercontent.com/88147124/220116955-03b44ac3-aafd-4516-80dd-1df0dec2c124.mp4

**Comment by sasha-astiadi** [comment]
@amandacaster its supposed to send you to outlook, or to gmail, or anything that you use for mailing

**Comment by sasha-astiadi** [comment]
@amandacaster its not gonna send you to pop up contact form.

**Comment by sasha-astiadi** [comment]
https://user-images.githubusercontent.com/43240801/220576888-64369321-2b61-472a-8331-c56db673b750.mov

**Comment by amandacaster** [comment]
> @amandacaster its not gonna send you to pop up contact form.

I will try on another browser, as you see in the video I sent it was not taking me anywhere. Thanks @sasha-astiadi.
