### ISSUE TITLE
Website : Artheon : Proofread - Errors found

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/home#269]
Website : https://artheon.co/

Website Repository: https://github.com/freeflowtribe/www_artheon

Errors found: -

1) The button " Learn More About TFT" redirects to the website https://threefold.io/token.html showing a blank page.

2) Also, the button "Visit ACI" at the end of the page redirects to https://www.consciousinternet.org/ that is showing an error "Secure connection failed"

**Comment by sasha-astiadi** [comment]
- [ ] fix the link to https://www.threefold.io/tft/
- [ ] remove ACI altogether
