### ISSUE TITLE
enable veda.university

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#27]
## give form to veda online project

- name = veda.university
- https://github.com/orgs/veda-university

## goal

- create a virtual team which will manage this project
- put in place the basic infrastructure
- put basic first info in place (can be very small to start with)

## Deliverables 
- [ ] make sure Anton, Ampara know the basics about github, gdrive...
- [ ] create docs.grid.tf account (access to despiegk, nbabenko, ...)
- [ ] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [ ] make sure website & wiki are on our publishing platform exposed (production,staging)
- [ ] use mobirise with std mobirise theme 4 as basics
- [ ] create space on freeflowpages
- [ ] give team access to the multiple parts
- [ ] make sure all photos are on their gdrive

## requirements

- < 2 man days work !!!
- its just a starting point so team can continue

## remarks

- team will use email domain veda.online also for this one

**Comment by Sacha96** [comment]
@despiegk please confirm if the above is still relevant. Thanks!
