### ISSUE TITLE
Website : FreeFlow twin : Proofread : Errors

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldfoundation/home#270]
Website: https://www2.freeflow.life/

Website repository: https://github.com/freeflowuniverse/www_freeflow_org

Errors : 

#TWIN PAGE

1) "Know more" button doesn't work.

2) "Get the twin" button on the top & bottom of the page leads to a 404 error "https://threefoldfoundation.github.io/books/freeflow/network/buy/buy_my_twin.html"

3)"More info" button leads to a 404 error.

#NODEPAGE

1) "Know More" button redirects to https://threefoldfoundation.github.io/books/freeflow/network/farming/farming_intro.html which is a 404 error

2)" Full Details" button redirects to https://threefoldfoundation.github.io/books/freeflow/network/farming/farming_intro.html which is a 404 error.

3) Same with the "See Rewards" button on the Node page.

#TAKE A PART

1) "Know More" button on the Acquire CHI redirects to https://threefoldfoundation.github.io/books/freeflow/network/buy/buy_my_chi.html which is a 404 error.

**Comment by sasha-astiadi** [comment]
- [ ] remove know more button 0n twin
- [ ] update link to https://threefoldfoundation.github.io/books/freeflow/freeflow/buy/buy_my_twin.html to buy twin
- [ ] update know more node link to https://threefoldfoundation.github.io/books/freeflow/freeflow/network/farming/node_buy.html
- [ ] update full detail link to - https://threefoldfoundation.github.io/books/freeflow/freeflow/network/farming/farming_intro.html
- [ ] reward link to https://threefoldfoundation.github.io/books/freeflow/freeflow/network/farming/farming_reward.html
- [ ] chi link https://threefoldfoundation.github.io/books/freeflow/freeflow/buy/buy_my_chi.html
- [ ]
