### ISSUE TITLE
Proofread : Website - FreeFlow : Errors 

### ISSUE THREAD

**Issue by TullysInc** [threefoldfoundation/home#271]
Website Repo: https://github.com/freeflowtribe/www_freeflownation

1. Privacy Policy in the footer section at the bottom re-directs to missing policy page: https://docs.google.com/document/u/1/d/1SHLKJBdZHtGrb0p8OnfHUYsMtHPOf4sZPawpPWY8FtU/edit?usp=sharing
![image](https://user-images.githubusercontent.com/105203696/220407530-a9b62f79-2bcf-4659-84b5-3b8b08898121.png)

2. Conscious Internet Alliance - "Learn More" button directs to  "www.consciousinternet.org invalid response."
![image](https://user-images.githubusercontent.com/105203696/220408866-b07ec178-abc1-46bf-97d5-b2a57475a054.png)
![image](https://user-images.githubusercontent.com/105203696/220408954-5731a622-06af-415d-899e-67f2416ac105.png)

3. Projects: Gold Flow Token: "Learn More" button directs to site can't be reached: https://goldflow.io/
![image](https://user-images.githubusercontent.com/105203696/220410989-577e21f3-b41d-42f5-9988-c0a7d82ce681.png)

4. Projects: FairSwap: https://freeflownation.org/page19.html - "Learn More" button directs to site can't be reached: https://www2.fair-swap.org/
![image](https://user-images.githubusercontent.com/105203696/220411722-954fb7f7-9e30-4fa2-9ca8-db1cb8e25325.png)

5. Homepage: FreeFlow Matchmakers: "Learn More" button directs to site can't be reached: https://www.freeflowmatchmakers.com/
![image](https://user-images.githubusercontent.com/105203696/220412664-03985159-be58-469f-9c7c-5d23e3391a5c.png)

**Comment by sasha-astiadi** [comment]
- [ ] update legal link to https://library.threefold.me/info/legal/#/
- [ ] remove Conscious Internet Alliance
- [ ] remove goldflow
- [ ] redir fairswap button to https://incubaid.com/fairswap.html
- [ ] remove ff matchmakers
