### ISSUE TITLE
Proofread : Website - OurNomad : Errors 

### ISSUE THREAD

**Issue by TullysInc** [threefoldfoundation/home#272]
Website Repo: https://github.com/ourworld-tsc/www_ournomads

1. Homepage: ""Know More" doesn't click through to any wesbite or URL:
![image](https://user-images.githubusercontent.com/105203696/220414308-d9912170-1b8f-4c7d-8cfb-e7d1686ef5d8.png)

2. Homepage: "Our Locations" is re-directing back to the top of the home page:
![image](https://user-images.githubusercontent.com/105203696/220414573-60a885cb-05d2-4c50-a1e3-ad3bc1eb39e7.png)
![image](https://user-images.githubusercontent.com/105203696/220414864-58b2707c-a45c-4a94-a52c-dd644c4d9d3b.png)

3. Invest: Majority of the property images are not showing under the Invest page:
![image](https://user-images.githubusercontent.com/105203696/220415864-785aa787-5070-40a7-a349-cffc3de413dc.png)

**Comment by Sacha156** [comment]
@sasha-astiadi I've directed the buttons on the home page and added the images on the invest page.

**Comment by samtaggart** [comment]
@sasha-astiadi The "invest" page is the exact same as the "locations" page. This seems to be an error. Do you know what content should go on the "invest" page?

**Comment by Sacha156** [comment]
All changes where made on a separate branch

**Comment by samtaggart** [comment]
> @sasha-astiadi The "invest" page is the exact same as the "locations" page. This seems to be an error. Do you know what content should go on the "invest" page?

Ping here.

**Comment by sasha-astiadi** [comment]
@samtaggart let me check the local files

**Comment by sasha-astiadi** [comment]
@samtaggart i checked, and previously was just an image of the beach and a contact us info@ourworld.tf button.

but thers a new edit in the doc: https://docs.google.com/document/d/1RuWIVcuhSE5BGF1HkgXqKVOcF31g0CQR-EjhcAAlHoA/edit?usp=sharing

eden token? idk if kds want it public or no

**Comment by sasha-astiadi** [comment]
everything has been fixed live on nomads.ourworld.tf
