### ISSUE TITLE
Proofread : Website - OurParadise

### ISSUE THREAD

**Issue by shng4you** [threefoldfoundation/home#273]
Website Repo: https://github.com/ourworld-tsc/www_ourparadise
Website: https://ourparadise.ourworld.tf/

Homepage: Under the protection tab: "Read more tab," got an HTTP ERROR 404 
![HTTP ERROR 404](https://user-images.githubusercontent.com/95933607/222453964-39d3385e-cbc5-4a42-ac4f-fef4ab85b33a.jpg)

**Comment by sasha-astiadi** [comment]
@ehab-hassan please create a new folder with index.md like the other three programs, a folder called mbwenimangrove_pro.

text for index.md

title: Mbweni Mangrove Beach
subtitle: Conservation project to 5200 Seedlings of Mangroves Replant Seedlings at Mbweni Mangrove.


Paragraph 1:
The Mbweni Mangrove Protection Program is a dedicated conservation initiative aimed at preserving the pristine beauty and ecological significance of Mbweni Mangrove Beach. With a focus on sustainability and restoration, the program has successfully replanted an impressive 5200 seedlings of mangroves, contributing to the preservation of this vital coastal ecosystem. Mangroves play a crucial role in coastal protection, acting as a natural barrier against erosion and storm surges while providing a habitat for various marine species. The Mbweni Mangrove Protection Program has not only nurtured these valuable seedlings but also raised awareness among local communities and visitors about the importance of mangrove conservation for the well-being of both the environment and the people.

Paragraph 2:
Nestled in the heart of paradise, the Mbweni Mangrove Beach has become a beacon of hope for sustainable environmental practices and a model for successful conservation efforts. The tireless efforts of the Mbweni Mangrove Protection Program have fostered a thriving mangrove ecosystem, creating a sanctuary for diverse wildlife and enhancing the natural beauty of the beach. Through community engagement and collaborative partnerships, the program has not only revived the fragile mangrove habitat but also empowered local residents to take an active role in protecting their environment. As visitors to Mbweni Mangrove Beach, we have the unique opportunity to witness the positive impact of the program firsthand and become advocates for preserving this ecological gem for generations to come.


images: 

[Archive.zip](https://github.com/threefoldfoundation/home/files/12162940/Archive.zip)

**Comment by ehab-hassan** [comment]
done

![image](https://github.com/threefoldfoundation/home/assets/10484295/2d0ceb71-d869-4318-8398-fb27a4c7b643)
