### ISSUE TITLE
TF Cloud Website Issues

### ISSUE THREAD

**Issue by Ashishban** [threefoldfoundation/home#275]
URL - https://cloud.threefold.io/

On Home page, "Discover the Marketplace" button is not working.
 
<img width="680" alt="1" src="https://user-images.githubusercontent.com/91247662/223984903-0faad0ae-8c29-4c37-8187-f8c76fadb757.png">

**Comment by ehab-hassan** [comment]
@sasha-astiadi what is the new link for marketplace?

**Comment by sasha-astiadi** [comment]
- [ ] ThreeFold PlayGround

Playground is a user-friendly web-based interface that serves as a sandbox environment for developers, allowing them to experiment, test, and deploy their applications on the ThreeFold Grid.

button: https://play.grid.tf

**Comment by ehab-hassan** [comment]
@sasha-astiadi I discussed with Thabet and put the new playground link  https://playground.grid.tf/

**Comment by ehab-hassan** [comment]
fixed
![image](https://github.com/threefoldfoundation/home/assets/10484295/9ab4bbec-adb7-42ad-80be-efee836e0a2d)
