### ISSUE TITLE
Clone website Zanzibar / Zola Tool

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#277]
Hey there!

We need to clone the website in Zanzibar (Jungle Paradise) below by using zola tool. The content of the website has to be cloned and can be found in the link with the log-in details below. The text and assets of the website are available with these log-ins.

websites.cloudbeds.com
[nurdidem@incubaid.com](mailto:nurdidem@incubaid.com)
Ed3n5Mil!

if any questions please comment/ reach out to me.

Priority to do on Monday as current website went down.. https://beach-resort-zanzibar.com/

Thank you

**Comment by sasha-astiadi** [comment]
@ehab-hassan lets talk about this as well on the call

**Comment by Karoline888** [comment]
I'm following, thank you

**Comment by ehab-hassan** [comment]
Repo is here
https://github.com/threefoldfoundation/www_jungle_paradise

Home is almost finished
staging
https://www2.jungleparadise.tf/

**Comment by Karoline888** [comment]
Great!!! Very happy!! Than you thank you for the update

**Comment by ehab-hassan** [comment]
all pages updated with Zola
https://www2.jungleparadise.tf/
