### ISSUE TITLE
Incubaid websitev4.0

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#278]
home page

- [x] add space <br>

on

We believe doing good for the world and doing business can go hand in hand. We are building companies which will help to achieve an ambituous global goal:

----

fix footer capitalization first letter

![Image](https://user-images.githubusercontent.com/43240801/232490996-9e37499e-7ecc-4efe-8c24-92bc48e220b5.png)

fix button capitalization first letter

![Image](https://user-images.githubusercontent.com/43240801/232491044-f32f0f06-df6b-4d6e-981b-3594c173742a.png)

**Comment by sasha-astiadi** [comment]
https://www2.incubaid.com/people/



![Image](https://user-images.githubusercontent.com/43240801/232491695-98ddbb01-c25f-482a-b54d-3a4c6c8a3e64.png)

should not be side to side

**Comment by sasha-astiadi** [comment]
![Image](https://user-images.githubusercontent.com/43240801/232503136-b7dd9d5e-624d-41f1-a7c3-128961893578.png)

capital letter

**Comment by sasha-astiadi** [comment]
![Image](https://user-images.githubusercontent.com/43240801/232503884-17665173-25ea-42ad-8e3e-27444116f753.png)

capital

**Comment by ehab-hassan** [comment]
https://www2.incubaid.com/
check please

**Comment by sasha-astiadi** [comment]
@ehab-hassan thanks ehab!
