### ISSUE TITLE
move freeflowpages to new location

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#28]
## move to new location

- https://github.com/freeflowpages -> myfreeflow

**Comment by nbabenko** [comment]
Lila expressed desire to help with ownership of the freeflowpages

**Comment by nbabenko** [comment]
https://docs.google.com/document/d/1nsHTZdItCHxkap0ilVKxs82Uiu_tloMZb8X9Vc6rt3s/edit
