### ISSUE TITLE
enable freeflowtokens

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#29]
## give form to freeflowtokens

- name = freeflowtokens.com
- https://github.com/orgs/freeflowtokens
- https://www.name.com/account/domain/details/freeflowtokens.com

## idea

- will be positioned as separate project which lives on top of the TF Grid
- gives free money to people

## goal

- enable a virtual team which will manage this project
- put in place the basic infrastructure
- put basic first info in place (can be very small to start with)

## Deliverables 

- [x] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [x] create docs.grid.tf account (access to despiegk, nbabenko, ...)
- [x] make sure website & wiki are on our publishing platform exposed (production,staging)
- [x] use mobirise with std mobirise theme 4 as basics
    - [x] move content, there is already content for this project, can be small
- [x] create space on exsting freeflowpages (if it doesnt exist yet)
- [x] look for people who will own this project

## requirements

- < 2 man days work !!!
- its just a starting point so team can continue

**Comment by nbabenko** [comment]
https://docs.google.com/document/d/1qoPiLHvDUXuna3f4KOUkmPbC8e4xnaLYSEnqK88v7yQ/edit

**Comment by nbabenko** [comment]
Task to deploy wiki: https://github.com/freeflowtoken/info/issues/1

**Comment by nbabenko** [comment]
Task to find project owner and define the team: https://github.com/freeflowtoken/home/issues/1
