### ISSUE TITLE
ww_eden mobile optimization

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#293]
https://zanzibar.ourworld.tf/home/

https://github.com/ourworld-tsc/www_eden

<img width="317" alt="Screenshot 2023-05-10 at 18 14 40" src="https://github.com/threefoldfoundation/home/assets/43240801/8c252bfb-71a7-430a-9110-8762ac3042da">

for all pages
- add left and right margin on all pages
- add padding above header on all pages
- header title size too big

- the gap between header section and next section too big
<img width="286" alt="Screenshot 2023-05-10 at 18 16 47" src="https://github.com/threefoldfoundation/home/assets/43240801/f9cfb068-4604-40be-bac6-e23967fba58f">

**Comment by ehab-hassan** [comment]
There a lot of issues in this website like text with black not clear at images the images size is very big working on it with mobile issue

**Comment by ehab-hassan** [comment]
done
https://zanzibar.ourworld.tf/

**Comment by sasha-astiadi** [comment]
we dont have staging for eden.... we can create one
