### ISSUE TITLE
ournomad mobile fix

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#294]
https://ournomads.ourworld.tf/

https://github.com/ourworld-tsc/www_ournomads

**homepage**

![Image](https://github.com/threefoldfoundation/home/assets/43240801/168e172e-1bc1-48a7-b36d-f21fbc34b857)

the gap is too big, maybe make the content have upper margin

![Image](https://github.com/threefoldfoundation/home/assets/43240801/59426267-dcf3-4af6-8ef0-fa23ac316d04)

pic can be a bit smaller

---

**coown** 

![Image](https://github.com/threefoldfoundation/home/assets/43240801/ac8be8d0-6e82-4cfd-b014-0dc660cbee27)

icon can be a bit smaller

**Comment by ehab-hassan** [comment]
done

![image](https://github.com/threefoldfoundation/home/assets/10484295/f82dc736-61b6-4480-9b04-b9e9aba6d867)

![image](https://github.com/threefoldfoundation/home/assets/10484295/af7d2bc6-c9d8-4049-b417-c06924d9d984)
![image](https://github.com/threefoldfoundation/home/assets/10484295/6595aea9-efed-499e-ac25-3f80eb003905)

**Comment by sasha-astiadi** [comment]
find new image that looks better on mobile, and desktop for the home header

**Comment by ehab-hassan** [comment]
@sasha-astiadi what u think?

![image](https://github.com/threefoldfoundation/home/assets/10484295/c069883e-6c5b-4dd4-865f-2d73ce26f55c) 
![image](https://github.com/threefoldfoundation/home/assets/10484295/bfde24b7-aa57-46e3-94dd-f5bb5189c9cd)

**Comment by sasha-astiadi** [comment]
@ehab-hassan its pretty  good! i like it! we can move on to prod i guess

**Comment by ehab-hassan** [comment]
https://github.com/threefoldtech/tf_operations/issues/1660

**Comment by ehab-hassan** [comment]
done updated
production https://ournomads.ourworld.tf/
staging https://www2.ournomads.ourworld.tf/
