### ISSUE TITLE
ourparadise mobile fix

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#295]
https://ourparadise.ourworld.tf/
https://github.com/ourworld-tsc/www_ourparadise

just need to add left right margin for all pages on mobile, maybe title header can be a bit smaller

![Image](https://github.com/threefoldfoundation/home/assets/43240801/a215c010-49d3-46f3-8c7e-f039ee7ee24f)

**Comment by ehab-hassan** [comment]
fixed all pages at mobile and desktop
I rechange margin for all sections and font size and images

![image](https://github.com/threefoldfoundation/home/assets/10484295/a78696e0-5147-4b88-a4ae-1f1ca85729de)

**Comment by sasha-astiadi** [comment]
nice! pls ask production to ops if done @ehab-hassan

**Comment by ehab-hassan** [comment]
https://github.com/threefoldtech/tf_operations/issues/1660

**Comment by ehab-hassan** [comment]
done update
production https://ourparadise.ourworld.tf/
staging https://www2.ourparadise.ourworld.tf/
