### ISSUE TITLE
fflife mobile optimization

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#296]
https://www.freeflow.life/

https://github.com/freeflowuniverse/www_freeflow_life

---

all header son all page needs:

left right margin
upper margin

![Image](https://github.com/threefoldfoundation/home/assets/43240801/e79515ea-adb6-41a0-82fa-30c2dd7f1dce)
![Image](https://github.com/threefoldfoundation/home/assets/43240801/e69e2aec-8ed8-4cd8-9984-f452c5f9f5ce)
![Image](https://github.com/threefoldfoundation/home/assets/43240801/1d5d3e52-4fa6-4ea2-aa88-ff8730b7b4a1)

**Comment by ehab-hassan** [comment]
fixed at production
