### ISSUE TITLE
threefold grid 1.0.1 life

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#30]
## threefold grid

- have a first usable version life of TF Grid

## goal

- have it all consistent
- have it good enough

# what

- ONLY meant for early adopter
- check 1.0.1 on https://freeflowpages.com/s/tf-grid-users/tasks/list

## high level deliverables for consistency

- [ ] all github content in threefoldfoundation account
- [ ] create docs.grid.tf account (access to despiegk, nbabenko, ...), or does it exist already
- [ ] create www_ repo's in github & example basic website (starting point)
    - [ ] move existing content in mobirise, there is content already, see andreas
- [ ] make sure website & wiki are on our publishing platform exposed
- [ ] make sure we link to space on freeflow page
- [ ] review all content on broken links, consistency
- [ ] review https://freeflowpages.com/s/tf-grid-users/tasks/list

## solutions ready to go

- [ ] Ethereum node example
- [ ] An Icecast node example
- [ ] Minecraft server
- [ ] Pastebin installation
- [ ] PeerTube installation
- [ ] A multiplayer quake server
- [ ] Odoo (ERP & Web Publishing system)
- [ ] Filemanager

what are requirements for each of the solutions

- buildable with prefab to flist
- deploy script as example in j.grid. needs ...

**Comment by nbabenko** [comment]
@andhartl , do we need a new website for it?

**Comment by nbabenko** [comment]
options: 
threefoldgrid.io
threefoldgrid.tech

**Comment by lilianacarrillo** [comment]
Here you find the website structure I could create: https://github.com/lilianacarrillo/grid
I have more time to help tomorrow.  Now busy with H2020 proposal with Solid.
