### ISSUE TITLE
make sure all websites have nmaster and staging branch

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#301]
- [x] make sure all websites on https://docs.google.com/spreadsheets/d/1RsCcmXt2ds4wWK-Tdp6KokyoGl-dEW96W84O89eiE4U/edit#gid=0 has master and dev branch / producting and staging
- [x] master branch for production www.
- [x] development for staging on www2.
- [x] make development branch as default
- [x] update readme on repo

**Comment by ehab-hassan** [comment]
https://github.com/threefoldtech/tf_operations/issues/1677

**Comment by sasha-astiadi** [comment]
done thank you @ehab-hassan
