### ISSUE TITLE
ourphone fixes

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#307]
[www_ourphone](https://github.com/ourworld-tsc/www_ourphone)

- [x] add another tab 'ourverse' on navbar, OURVERSE, when clicked, opening new tab to ourverse.tf
<img width="1402" alt="Screenshot 2023-07-12 at 12 01 43" src="https://github.com/threefoldfoundation/home/assets/43240801/d9ecf10f-33d5-40d1-8147-f1b22927cc8a">

- [x] limit width everywhere e.g. on https://ourverse.tf/use-cases/
![2023-07-12 12 05 55](https://github.com/threefoldfoundation/home/assets/43240801/02575dcb-c1d4-4e8d-ae78-85bbbaacdbf5)

- [x] https://github.com/ourworld-tsc/www_ourphone/issues/3
- [x] https://github.com/ourworld-tsc/www_ourphone/issues/2
- [x] make ourphone.tf  as main domain, redir ourphone.ourworld.tf to ourphone.tf

**Comment by samaradel** [comment]
> * [ ]  make ourphone.tf  as main domain, redir ourphone.ourworld.tf to ourphone.tf

@PeterNashaat @hossnys 
can you guys handle the redirect part, please?

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/tf_operations/issues/1789

**Comment by PeterNashaat** [comment]
> > * [ ]   make ourphone.tf  as main domain, redir ourphone.ourworld.tf to ourphone.tf
> 
> @PeterNashaat @hossnys can you guys handle the redirect part, please?

Done
