### ISSUE TITLE
enable open-meeting project

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#31]
## free video/audio conference service

- virtual company
- users need to have 3bot with TFT because they need to pay for tfgrid usage
- very simple value prop
    - everyone can communicate everywhere close to you
    - more efficient fact that it uses a box close to you

## goal

- create a virtual team which will manage this project
- put in place the basic infrastructure
- basic first content (can be small, just to get started)

## deliverables 
- [ ] rename account/website ... openmeeting
- [X] openmeeting.live exists
- [ ] make sure github access to despiegk, nbabenko, ...)
- [ ] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [ ] make sure website & wiki are on our publishing platform exposed
- [ ] create space on freeflowpages
- [ ] create dir in gdrive on tf extranet, create homepage
- [ ] migrate code created (see jonas) to new github account
- [ ] make sure all namings are ok 
- [ ] fill in roadmap on space in freeflowpages

**Comment by nbabenko** [comment]
@AdnanFatayerji @jdelrue , lets come up with a new name?

**Comment by nbabenko** [comment]
current website
http://www.remoteco.work/
current github: https://github.com/remotecowork/

**Comment by weynandkuijpers** [comment]
@nbabenko Ids this story still relevant to keep open?  Is it done , are there any updates?
