### ISSUE TITLE
make sure every website has favicon on browser

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#318]
![Image](https://github.com/threefoldfoundation/home/assets/43240801/29532442-4edd-49b2-a150-f9529da88d1d)

e.g ourworld doesnt

Incubaid zola | Incubaid | www_incubaid
-- | -- | --
Venture Creator studio | TF Foundation | www_venturecreator
ThreeFold | TF Foundation | www_threefold_io
GetTFT | TF Foundation | it_as_energy_shop
Ourphone | Ourworld Ventures | www_ourphone
OurNomad | Ourworld Ventures | www_ournomads
OurParadise | Ourworld Ventures | www_ourparadise
Ourworld | Ourworld Ventures | www_ourworld_tf
Zanzibar Ourparadise / eden | Ourworld Ventures | www_eden
Jungle Paradise Resort | Ourworld Ventures | www_jungle_paradise
Ourverse | Ourworld Ventures | www_ourverse
Freezone | Ourworld FreeZone | www_Ourworld_freezone
Mycelium | TF Foundation | www_mycelium
Freeflow Twin | FF Universe | www_freeflow_life

- [x] Incubaid zola	Incubaid	[www_incubaid](https://github.com/Incubaid/www_incubaid_zola)
- [x] Venture Creator studio	TF Foundation	[www_venturecreator](https://github.com/threefoldfoundation/www_venturecreator)
- [x] ThreeFold	TF Foundation	[www_threefold_io](https://github.com/threefoldfoundation/www_threefold_io)
- [ ] GetTFT	TF Foundation	[it_as_energy_shop](https://github.com/threefoldfoundation/it_as_energy_shop)
- [x] Ourphone	Ourworld Ventures	[www_ourphone](https://github.com/ourworldventures/www_ourphone)
- [x] OurNomad	Ourworld Ventures	[www_ournomads](https://github.com/ourworldventures/www_ournomads)
- [x] OurParadise	Ourworld Ventures	[www_ourparadise](https://github.com/ourworld-tsc/www_ourparadise)
- [x] Ourworld	Ourworld Ventures	[www_ourworld_tf](https://github.com/ourworldventures/www_ourworld_tf)
- [x] Zanzibar Ourparadise / eden	Ourworld Ventures	[www_eden](https://github.com/ourworldventures/www_eden)
- [x] Jungle Paradise Resort	Ourworld Ventures	[www_jungle_paradise](https://github.com/ourworldventures/www_jungle_paradise)
- [x] Ourverse	Ourworld Ventures	[www_ourverse](https://github.com/ourworld-tsc/www_ourverse)
- [x] Freezone	Ourworld FreeZone	[www_Ourworld_freezone](https://github.com/ourworldfreezone/www_ourworld_freezone)
- [x] Mycelium	TF Foundation	[www_mycelium](https://github.com/threefoldtech/mycelium)
- [x] Freeflow Twin	FF Universe	[www_freeflow_life](https://github.com/freeflowuniverse/www_freeflow_life)

**Comment by ehab-hassan** [comment]
@sasha-astiadi Some websites' logos are text like Ourworld ll put ThreeFold icon as favicon ok?

![image](https://github.com/threefoldfoundation/home/assets/10484295/35c21530-d99a-4b7a-9b39-4b64408891ea)

**Comment by sasha-astiadi** [comment]
its ok yes @ehab-hassan

**Comment by ehab-hassan** [comment]
@sasha-astiadi ok all done except [it_as_energy_shop](https://github.com/threefoldfoundation/it_as_energy_shop) I dont have access there`

**Comment by sasha-astiadi** [comment]
ok thanks ehab
