### ISSUE TITLE
remove people who left the company from all webs

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#319]
- [x] threefold
- [x] ourworld
- [x] freezone

gloria anne and perhaps others from egypt? @ehab-hassan are you updated on egypt team if anyone recently left?

**Comment by ehab-hassan** [comment]
@sasha-astiadi All Egypt Team updated and Gloria was Removed also.

**Comment by ehab-hassan** [comment]
done for all
