### ISSUE TITLE
enable coffee token project

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#32]
## enable farmers with coffee tokens

- TODO see weynand for content

## goal

- create a virtual team which will manage this project
- put in place the basic infrastructure
- basic first content (can be small, just to get started)

## deliverables 

- [x] choose name usable for github,name.com 
- [x] ask kristof to register name in name.com (so its in right account)
- [x] create github account (access to despiegk, nbabenko, ...), ask Kristof to create !
- [x] create docs.grid.tf account (access to despiegk, nbabenko, ...)
- [x] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [ ] make sure website & wiki are on our publishing platform exposed
- [x] create space on freeflowpages
- [ ] create dir in gdrive on tf extranet, create homepage

**Comment by nbabenko** [comment]
https://docs.google.com/document/d/138l1gRBkG-D9MYr2SmuCVuM_l64aqn34e5OwTifXOjw/edit

**Comment by nbabenko** [comment]
Separate task to define the team created: https://github.com/faircoffee-trade/home/issues/1
Separate task to deploy wiki created: https://github.com/faircoffee-trade/info/issues/1
