### ISSUE TITLE
enable goldtoken project

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#33]
## enable project

...

## goal

- create a virtual team which will manage this project
- put in place the basic infrastructure
- basic first content (can be small, just to get started)
 y
## deliverables 

- [x] choose name usable for github,name.com 
- [x] ask kristof to register name in name.com (so its in right account)
- [x] create github account (access to despiegk, nbabenko, ...), ask Kristof to create !
- [x] create docs.grid.tf account (access to despiegk, nbabenko, ...)
- [x] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [x] make sure website & wiki are on our publishing platform exposed
- [x] create space on freeflowpages
- [x] create dir in gdrive on tf extranet, create homepage

**Comment by nbabenko** [comment]
dns was already registered by Adnan. but we can transfer.

**Comment by nbabenko** [comment]
https://docs.google.com/document/d/1HMPhRHiEBpTsdFJpU-uCmC4sNle6V0rU9w5faEjkQSk/edit

**Comment by nbabenko** [comment]
Created separate task to deploy wiki: https://github.com/goldflow-io/info/issues/1

**Comment by nbabenko** [comment]
Created separate task to define project and the team: https://github.com/goldflow-io/home/issues/1
