### ISSUE TITLE
enable eur token project

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#34]
## enable project

...

## goal

- create a virtual team which will manage this project
- put in place the basic infrastructure
- basic first content (can be small, just to get started)

## deliverables 

- [x] choose name usable for github,name.com 
- [x] ask kristof to register name in name.com (so its in right account)
- [x] create github account (access to despiegk, nbabenko, ...), ask Kristof to create !
- [x] create docs.grid.tf account (access to despiegk, nbabenko, ...)
- [x] create info_ & www_ repo's in github & example basic wiki/website (starting point)
- [x] make sure website & wiki are on our publishing platform exposed
- [x] create space on freeflowpages
- [x] create dir in gdrive on tf extranet, create homepage

**Comment by nbabenko** [comment]
Who will be the team members and who is the owner of the project?

**Comment by nbabenko** [comment]
https://docs.google.com/document/d/1pkmStKeqn1Hm4Sm4Q1ZMV0lT-_kcR6ZcLyPmBFLY6Kg/edit

**Comment by lilianacarrillo** [comment]
@nbabenko should we add the team to this document? https://docs.google.com/spreadsheets/d/13PyfznZmOP0CvrbVsbPJL7TbLyHePs5KCtm_F_HEc7s/edit#gid=0

**Comment by lilianacarrillo** [comment]
@nbabenko Does this project need a different folder than the NBH-digital in here https://drive.google.com/drive/u/2/folders/1ww8CF3zPCVKhlyAhWO9WCqZZoHhA2hBl ?

**Comment by nbabenko** [comment]
@lilianacarrillo , yes, we need to understand who is the team and
folder - its ok to keep it in child folder of NBH-Diligtal

**Comment by nbabenko** [comment]
Everything is done, except
1. Populate the team, a separate task created: https://github.com/euroflow-io/home/issues/1
2. Deploy wiki, a separate task created: https://github.com/euroflow-io/home/issues/2

Closing this issue for now.

**Comment by nbabenko** [comment]
Created task to define the team: https://github.com/euroflow-io/home/issues/3
