### ISSUE TITLE
proof of tfgrid use part 1 (v1.0.1)

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#44]
on https://freeflowpages.com/s/tf-grid-users/

- [x] all tutorials & deployment scripts in https://github.com/myfreeflow/kosmos/
- [x] video how to deploy a quake server & how to use it from externally 
- [x] video how to deploy https://github.com/mickael-kerjean/filestash on top of local minio S3 server (without zdb backend) & how to use (needs to be wow effect)

do separate messages per workload so we have 2x news

### remarks

- see /sandbox/lib/jumpscale/kosmos/tutorials/odoo
- example how a tutorial needs to be implemented
- use branch development_installer
- to install this repo do: ```jsx modules-install --url=https://github.com/myfreeflow/kosmos```

**Comment by serboctor** [comment]
@despiegk can you give me access to push to myfreeflow/kosmos?

**Comment by zaibon** [comment]
@serboctor in the mean time, fork an create  PR with your code, so we can see progress. Thx

**Comment by serboctor** [comment]
Kristof and Reem agreed it is better to have the tutorials files under threefoldtech so I pushed them here https://github.com/threefoldtech/tutorials/tree/master/tutorials following the same structure and approach in the old repo.

**Comment by zaibon** [comment]
ok then. What about https://github.com/threefoldfoundation/info_grid/tree/development/docs/capacity_reservation ? This is not duplicated content

**Comment by serboctor** [comment]
The tutorials that Kristof wanted from what I understood from his odoo example, are functions that run all the steps with a brief read me, not a doc tutorials kind of thing. That why a user can run it from the shell.
So I created two tutorials one for quake3 and one for filestash. Both tutorials create the container using the right flist, and upload any files that need to be uploaded to the container.
I also created videos that I am uploading right now that demonstrate the steps inside the tutorials but from the kosmos shell step-by-step and also show which tutorial to run if you don't want to perform the steps yourself. In case of filestash, it also shows how you can configure it to connect to minio and use it.

**Comment by serboctor** [comment]
@despiegk I've uploaded the videos here https://drive.google.com/drive/folders/1tmX0CoSkRm2cQJmDtz29cDKn_Lq2g6l4?usp=sharing so can you please check them out. 
and I pushed `j.tutorials.quake3` and `j.tutorials.filestash` [here](https://github.com/threefoldtech/tutorials/tree/master/tutorials).

**Comment by zaibon** [comment]
> The tutorials that Kristof wanted from what I understood from his odoo example, are functions that run all the steps with a brief read me, not a doc tutorials kind of thing. 

All the tutorial in https://github.com/threefoldfoundation/info_grid/tree/development/docs/capacity_reservation are full example any one can run too. All the code is there. We could add next to the .md a .py file with just the code if needed. 

Also, should we move all the documents from info_grid somewhere else ? I though info_grid was the source of our wiki. And wiki is supposed to be the source of documentation.
Now seems we're spreading in different directions again.

**Comment by despiegk** [comment]
lets indeed see what we put where, info_grid is indeed source of info for grid

docs/capacity_reservation is maybe not the ideal location for everything we do its becoming more than capacity_reservation is about all kinds of tutorials where people can learn how to do something on the grid, I am sure it will become much more

lets together decide where we put it, good thing is we have it (-:

**Comment by zaibon** [comment]
Great. So should we rename this `docs/capacity_reservation` to something more generic ?
Or move it into an already existing folder that already have some developers oriented content ?

**Comment by zaibon** [comment]
Actually there is already a `docs/developers` and it even seems the documentation from `capacity_reservation` has been copied over there: https://github.com/threefoldfoundation/info_grid/tree/development/docs/developers
So this is not that good, we have now 3 time the same content, most probably all out of sync

**Comment by serboctor** [comment]
I agree that we shouldnt have docs scattered all over the place but I also feel it is a bit icky to just throw some python files in there that adds functionality to the `j.tutorials` extension.

**Comment by zaibon** [comment]
@serboctor yeah you're right. If the goal is to actually add some code into the `j` tree, then yeah the python file doesn't belong in the info_grid.

**Comment by Sacha96** [comment]
@zaibon @serboctor can we close this issue?
