### ISSUE TITLE
odoo 3bot login module

### ISSUE THREAD

**Issue by Hamdy** [threefoldfoundation/home#46]
A module to integrate 3bot login to odoo

**Comment by Hamdy** [comment]
https://github.com/threefoldfoundation/threebotlogin_odoo

**Comment by Sacha96** [comment]
@Hamdy any updates on the above? Regards.

**Comment by Hamdy** [comment]
@Sacha96 https://github.com/threefoldfoundation/threebotlogin_odoo
will need to be updated though in future, coz of some changes in how 3bot loign works
so may be by the next release we can update that code again
