### ISSUE TITLE
cleanup the account

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#52]
see https://github.com/orgs/threefoldfoundation/projects/8

- lots of them should be put on milestone next, and taken off this project because we cannot do them in 3 days
- go over all issues and put on now -> link to project
- or later or next
- for all issues in this account for threefoldfoundation

**Comment by despiegk** [comment]
there is already next project defined as well for the ones we need to do <2 weeks

**Comment by samtaggart** [comment]
Everyone please handle your own issues asap. If not, Sacha & I will make our best judgment with things. Thanks!

**Comment by VonSub** [comment]
everything in that project is listed done, can we close this @despiegk ?
