### ISSUE TITLE
forum protection

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#59]
- only in support and other well chosen categories people can post without moderation
- no unknown category
- make sure we have groups setup to do the moderation

**Comment by VonSub** [comment]
I was going to test some settings on our staging version of the forum. but hit multiple snags.

- staging 3bot connect not in testflight (being worked on as we speak)
- login broken for staging (tested with @gmachtel as he had staging app available, bug reported)

**Comment by VonSub** [comment]
Support team handles incoming topics on workdays.
I'm on duty on Fridays and Geert on Saturdays.

Going with that setup for a 2 week trial to see how that works.
Telegram group between members also setup.
