### ISSUE TITLE
Voting system for tech council

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/home#67]
Prequisites:

- [x] [Add the possibility to manage account data to the stellar client](https://github.com/threefoldtech/js-sdk/issues/352)
- [ ] [allow multisig on an account's data-entries in the stellar client](https://github.com/threefoldtech/js-sdk/issues/353)

**Comment by sasha-astiadi** [comment]
@robvanmieghem  is this resolved? please confirm / close or ill transfer this issue to the latest project
