### ISSUE TITLE
websites/wikis upgrade

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/home#68]
- [x] move pages https://github.com/threefoldfoundation/www_deployment_robot/tree/master/src/ideas into [i9 wiki](https://github.com/threefoldfoundation/info_internet9) @hossnys 
  - [x] delete [www_deployment_robot ](https://github.com/threefoldfoundation/www_deployment_robot) @hossnys 
- [x] move www_threefold.me into https://github.com/threefoldfoundation/www_tffoundation with a proper branch (development_threefoldme) @xmonader 
- [x] update [websites](https://github.com/threefoldfoundation) repo (to have proper build) @Pishoy  disabled consciousinternet and community servers until they upgrade

# Threefold.io related TFGrid Web Presence: threefold.io domain
- [x] Threefold.io (should serve the same site of cloud.threefold.io "the tech website")  blocked on https://github.com/threefoldfoundation/www_tfgrid/issues/17 
  - [x] website repo [www_tfgrid](https://github.com/threefoldfoundation/www_tfgrid) on  threefold.io
  - ~[] wiki [info_tfgrid](https://github.com/threefoldfoundation/info_tfgrid) on wiki.threefold.io and info.threefold.io~
- [x] [manuals/tutorials info_tfmanual](https://github.com/threefoldfoundation/info_tfmanual) hosted on manual.threefold.io (keep sdk.threefold.io too)
- [x] [farmers](https://github.com/threefoldfoundation/www_farmer_threefold.io) hosted on farmer.threefold.io
- [x] [freetft](https://github.com/threefoldfoundation/www_getfreetft) hosted on getfreetft.threefold.io
- [x] [blog](https://github.com/threefoldfoundation/www_tfblog) hosted on blog.threefold.io and the config is updated for publishingtools
- [x] threefold.tech is alias for threefold.io @hossnys 

# TFFoundation presence on threefold.me/foundation
- [x] threefold.me [foundation website](https://github.com/threefoldfoundation/www_tffoundation) hosted on threefold.me
  - [x] the wiki for the foundation https://github.com/threefoldfoundation/info_tffoundation hosted on wiki.threefold.me and 
info.threefold.me and also wiki.threefold.io, info.threefold.io
  - [x] [deploy prod, staging websites](https://github.com/threefoldfoundation/www_tffoundation/issues/266)

- [x] community [www_community](https://github.com/threefoldfoundation/www_community) hosted on community.threefold.me
- [x] aci [ACI](https://github.com/threefoldfoundation/www_conscious_internet) hosted on consciousinternet.org
- [x] [internet9](https://github.com/threefoldfoundation/info_internet9) hosted on internet9.me & info.internet9.me
- [x] threefold.foundation is alias for threefold.me 

# remarks
- make sure to update all the links of the updated domains on all of the wikis and websites.
- make sure you are using the right urls for the git repos everywhere (3bot deployment, publishingtools, caddy... etc)

**Comment by despiegk** [comment]
CHECK WITH https://circles.threefold.me/project/despiegk-tftech-software/us/127
needs to be in line with that
