### ISSUE TITLE
changes to sales bot 

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#70]
https://selltfta.threefoldtoken.com/#/

- [ ] mention sales bot can sell on liquid, btcalpha & stellar
- [x] mention that any sales done gets distributed over the open orders
- [x] mention that people will be able to specify the specific price in a next version

**Comment by ranatrk** [comment]
>     * mention that any sales done gets distributed over the open orders

![Screenshot from 2020-07-22 12-57-29](https://user-images.githubusercontent.com/17128393/88168590-f03d8100-cc1a-11ea-8f84-ee11addaf56a.png)


>     * mention that people will be able to specify the specific price in a next version

![Screenshot from 2020-07-22 12-17-43](https://user-images.githubusercontent.com/17128393/88168470-c1bfa600-cc1a-11ea-89b0-e4c71260e8ce.png)

**Comment by ranatrk** [comment]
>     * mention sales bot can sell on liquid, btcalpha & stellar
 will not be updated for now

**Comment by robvanmieghem** [comment]
We legally have to be careful how to phrase that

**Comment by robvanmieghem** [comment]
Liquid  and Btc-alpha do not list XLM.

**Comment by sasha-astiadi** [comment]
@robvanmieghem is this resolved? please confirm / close or ill transfer this issue to the latest project

**Comment by robvanmieghem** [comment]
First issue not but will be deprecated soon
