### ISSUE TITLE
Dashboard with tfta/tft insights and stats

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/home#71]
Nicely show how many TFT,TFTA andFreeTFT are available, how many are blocked until when, the data will come from a webservice running on js-ng which is still under development.

Technical Requirements
- [x] [scripts to get some insight and stats](https://github.com/threefoldfoundation/tft-stellar/issues/179)
- [x] [rest service to get tft/tfta insight and stats](https://github.com/threefoldfoundation/tft-stellar/issues/182)

**Comment by abdulgig** [comment]
@robvanmieghem , based upon discussion today, just a mockup . . 

![Token_Dashboard](https://user-images.githubusercontent.com/25789764/88335210-f8dda680-cd43-11ea-9142-f262e98b5f7e.png)

**Comment by robvanmieghem** [comment]
@abdulgig  looks great, what exactly is the definition of "In use"?

**Comment by abdulgig** [comment]
@robvanmieghem that will be changed. Any other changes in terminology / labels / statistical data, we will sort out in the call with you on Monday.

**Comment by sasha-astiadi** [comment]
@robvanmieghem @abdulgig  is this resolved? please confirm / close or ill transfer this issue to the latest project

**Comment by xmonader** [comment]
APIs provided from js-sdk side. https://github.com/threefoldfoundation/tft-stellar/issues/182

**Comment by abdulgig** [comment]
@sasha-astiadi  . . Would be finished by end of this week

**Comment by abdulgig** [comment]
Based upon the REST service, dashboard for TFTs / TFTa under this link,

https://tokenstats.threefoldtoken.com

Few Issues,

1. The REST service doesn't return any data for FreeTFTs , tracked [here](https://github.com/threefoldfoundation/tft-stellar/issues/196)
2. Without specifying the token code in the call, we should get the stats for TFT, TFTA and FreeTFT

![image](https://user-images.githubusercontent.com/25789764/89623472-b2d92480-d8a5-11ea-9dda-d181536b4c4d.png)
