### ISSUE TITLE
Add Free cookie Consent to all digital resources that collect data to comply with ePrivacy Directive & GDPR.

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/home#72]
Wether websites, wiki and/or marketplace, we need to make sure we comply with the latest GDPR regulations. This involves that we have to notify our site's visitors that we're using cookies and that we must obtain their consent for cookie usage.

Recommended to use this - takes 2 min - creates code to add to Code =

https://www.freeprivacypolicy.com/free-cookie-consent/

**Comment by Sacha96** [comment]
@maximilianrang I would also recommend to put the box directly on the main page so they fill it in without needed to click - better user flow (less steps involved) :)

**Comment by maximilianrang** [comment]
@Sacha96 ok, lets do it this way

**Comment by Sacha96** [comment]
stories have been created in the right repos with new scripts to comply with cookie consent policy of GDPR
