### ISSUE TITLE
host strategy wiki on web platform

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#73]
## on strategy.threefold.me

with passwd: ask Kristof which one

https://github.com/threefoldfoundation/info_strategic: branch master

## on funding20.threefold.me

with passwd: ask Kristof which one

https://github.com/threefoldfoundation/info_strategic: branch funding20

**Comment by despiegk** [comment]
branch still needs to be created

**Comment by hossnys** [comment]
changes are here : https://github.com/crystaluniverse/publishingtools/pull/201

two wikis are live now https://strategy.threefold.me/#/ , https://funding20.threefold.me/#/

credentials with @xmonader
