### ISSUE TITLE
Grid website

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/home#77]
![image](https://user-images.githubusercontent.com/64129/99557580-861bc980-29cb-11eb-883a-4e3ed3673c13.png)

- [ ] website repo
- [ ] gridsome based

## pages
- [ ] What is the grid (with infographics)
  - [ ] explainer videos
  - [ ] how it works
    - [ ] infographics
    - [ ] farming link
- [ ] TFT
  - [ ] tokenomics light 
   -  [ ] infographics
  - [ ] TFT ecosystem infographics
  - links to 
   - [ ] Explorer
   - [ ] Simulator
   - [ ] tokens wiki 
- [ ] partners (existing ones)
- [ ] Running on top of the grid 
  - links to
    - [ ] 3Bot
    - [ ] VDC
    - [ ] Threefold now
    - [ ] crystaltwin.me
    - [ ] protocol.me

**Comment by maximilianrang** [comment]
We received an update from @despiegk yesterday and will follow up with a new version of the mindmup.
