### ISSUE TITLE
ALL - Github cleanup

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#78]
## Issues

- there are old issues
- there are dangling branches (branches not used or not up to date)
- add default tags are not in each repo
- the project mgmt is not done (release mgmt)

## checklist for each wiki & website

- [x] make sure there is master & development branch
- [x] make sure all changes from master are in development branch
- [x] make sure the default tags & labels are on each repo
- [x] make project on account level on foundation called web2.5 (do common here so its easier to track work over all repo's)
- [x] make project on account level on foundation called web2.6
- [x] make sure we have this project 'web2.5' & web2.6 available on each project
- [x] sort over all issues on each repo make sure now,next,later milestone used,and the now linked to project 2.5 or 2.6
- [x] make sure we only have master & development for now
    - [x] if need for an unstable branch it should be development_ameaningfullname
- [x]  tag issues to 'now' 'next' or 'later'

## remark

all the sites & wiki's we have can be found on https://github.com/crystaluniverse/vlang_tools/blob/development/installers/myconfig/config.v

**Comment by Vilnite** [comment]
I'm not following the naming:  **web2.5** & **web2.6**
Did this for foundation's current ongoing projects:
<img width="1319" alt="Screenshot 2021-02-09 at 11 34 37" src="https://user-images.githubusercontent.com/20182572/107344246-ebfb8700-6aca-11eb-966a-740fabd62fe3.png">

Please lmk and help understand naming overall standard if there's one.

**Comment by Vilnite** [comment]
For branches to keep in clean and consistent this works very well so far:
development: working  branch for anyone involved
staging: staging branch
master: production branch
