### ISSUE TITLE
ALL - content related to wallets need to be on right spot

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#85]
- all wallet info to do with threefold connect -> info_foundation
- all wallet info to do with 3bot (evdc controller) -> info_cloud
- only some info on the wallet available in the 3Bot dashboard -> info_sdk
- all wallet references in sdk point to wallet info in info_foundation or info_cloud

**Comment by despiegk** [comment]
means close https://github.com/threefoldfoundation/info_tfgrid_sdk/issues/227

**Comment by samtaggart** [comment]
I won't have time to get to this today and was just assigned yesterday so I'm going to move to next sprint.

**Comment by samtaggart** [comment]
I will handle this on Sunday.

**Comment by samtaggart** [comment]
I'm untagging myself from this issue. @gmachtel said he can handle but potentially not this week so I will move to next sprint.
