### ISSUE TITLE
ALL - WIKI SPLIT

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#88]
TF Wiki's content needs to be split between:
- [x] Main wiki = info_threefold (work on **info_foundation_archive** for now until ready, then push to info_threefold)
- [x] TF Manual = info_tfgrid_sdk
- [x] DigitalTwin wiki = info_twin
- [x] Cloud wiki = info_cloud
- [x] TF Tech wiki = info_tech
- [x] TF Legal wiki = info_legal

**Comment by Vilnite** [comment]
Blocked until all wiki errors are fixed:  https://github.com/threefoldfoundation/home/issues/89

**Comment by despiegk** [comment]
see overview on

http://localhost:9998/threefold/#/overview_sites.md
