### ISSUE TITLE
ALL - Fix all wiki errors

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#89]
- [x] info_threefold / info_foundation_archive (@VonSub)
- [x] info_tech (@VonSub)
- [ ] info_cloud (@gmachtel)
- [ ] info_tfgrid_sdk (@gmachtel)
- [x] info_twin (@samtaggart)
- [x] info_legal (@VonSub)

Take these steps first:
$ publishtools update
$ publishtools version (should be 1.0.4)
$ publishtools install
$ publishtools pull
$ publishtools develop

Then check and fix errors on your assigned wiki's:
http://localhost:..

"Best way to fix include errors is by using find function, then you see the 2 docs and you can remove one."

$ mc 
ctrl + O (on / off)

$ find . (will find everything)
$ find . | grep <name_of_what_you_look_for>

Good luck!

**Comment by sasha-astiadi** [comment]
<img width="581" alt="Screenshot 2021-02-17 at 12 39 45" src="https://user-images.githubusercontent.com/43240801/108226280-0bcf2280-713d-11eb-9815-22dcafab97a1.png">
just FYI on legal @Vilnite

**Comment by samtaggart** [comment]
@VonSub is on this

**Comment by VonSub** [comment]
> @VonSub is on this

I'm on TF Foundation, but stuck for now.
Talking to @gmachtel to have him and @sasha-astiadi fix errors in Manual as I'm unfamiliar with most of the documents featured there.

**Comment by samtaggart** [comment]
We did as much as we could. Going to wait until @despiegk fixes some bugs on publishtools and pick it back up.

**Comment by samtaggart** [comment]
@Vilnite Recommend we move this issue into next week.

**Comment by VonSub** [comment]
fixed all in I could in TF foundation, Tech, Legal.

**Comment by samtaggart** [comment]
@VonSub There are new errors. Recommend you take a look.

I will handle Cloud & Twin.

**Comment by VonSub** [comment]
Foundation: Need guidance on what we do with the mentioned people in the errors. besides that we only have errors from a beta-file. (sidebar_todo)

**Comment by VonSub** [comment]
Fixed foundation this morning, and now missing stuff again... I think when we're all moving parts we'll never get a completely clean slate.

**Comment by VonSub** [comment]
Legal: no issues
Tech:

1 File I have no idea about
1 Error on the sidebar which we need to ignore 
2 includes from the Bettertoken wiki not being included.

**Comment by samtaggart** [comment]
Errors are all fixed on Digital Twin.

**Comment by samtaggart** [comment]
I see this to be an endless task to be honest especially while there is still a lot of editing / merging / work on the publish tools going on.

**Comment by samtaggart** [comment]
Just going to close this one out and it's going to be an ongoing task to correct these. We'll check one last time before we push the wikis live.
