### ISSUE TITLE
ALL - remove dark mode from all websites

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#91]
Please remove dark mode from all websites (except www_threefold_tech) completely.

We removed theme switch but people who has dark mode by default on their computers (like Kds) sees our websites in dark mode, without option to switch to light mode. 
That's a bad experience.

Please remove dark mode completely for:
- [x] www_threefold_io
- [x] www_threefold_cloud
- [x] www_threefold_farming
- [x] www_threefold_twin
- [x] www_threefold_marketplace
- [x] www_conscious_internet

Please remove white mode completely for:
- [x] www_threefold_tech

**Comment by ehab-hassan** [comment]
( www_threefold_io) updated development & master
 (www_threefold_cloud) updated development 
 (www_threefold_farming) updated development & master
 (www_threefold_twin) updated development 
 (www_conscious_internet) updated development
