### ISSUE TITLE
Marketplace Web - cleanup

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#93]
- [ ] now.threefold.io : which is the commercial website about marketplace and has all solutions described (team promotion)

- [ ] content from gridsome wiki ex now.threefold.io -> the new now.threefold.io which is based on new web framework (team promotion)

- [ ] on each commercial page there is "deploy now button" -> go to auth page, see who user is, redirect to their evdc and their marketplace for that solution

- [ ] if you don't exist, ask to install TF Connect

**Comment by sasha-astiadi** [comment]
please put it ijn the right repo / project @Vilnite

**Comment by Vilnite** [comment]
see #10
